import type { HomeMusicTrack } from "@/types/homeLiving";

/**
 * Generated by `npm run music:audit-audius`.
 * The build environment used to create Phase 14L has no outbound Audius access,
 * so the initial manifest is intentionally empty. On a machine/CI runner with
 * Internet access, the audit writes exact provider IDs here and records unmatched
 * seeds so runtime does not repeatedly search for tracks Audius does not carry.
 */
export const VIETNAMESE_MUSIC_PROVIDER_AUDIT_VERSION = "vi2-dynamic-2026-09-30" as const;
export const VIETNAMESE_MUSIC_PROVIDER_AUDIT_GENERATED_AT: string | null = null;
export const PREAUDITED_VIETNAMESE_TRACKS: HomeMusicTrack[] = [];
export const AUDIUS_UNMATCHED_SEED_IDS: string[] = [];
export const AUDIUS_AMBIGUOUS_SEED_IDS: string[] = [];
