import { randomUUID } from "node:crypto";
import { performance } from "node:perf_hooks";
import { createInitialXiangqiState, playXiangqiMove } from "./xiangqiEngine.js";
import { XiangqiDomainError, type PersistedXiangqiGame, type PublicXiangqiGameState, type XiangqiColor, type XiangqiMoveAck, type XiangqiMoveDelta, type XiangqiTimeControl } from "./xiangqiTypes.js";
import { XiangqiPersistenceService } from "./xiangqiPersistenceService.js";

type AwayBudget={deadlineMono:number;remainingAtLeaveMs:number};
type Runtime={game:PersistedXiangqiGame;turnStartedMono:number|null;connectedUids:Set<string>;readyUids:Set<string>;boardAwayByUid:Map<string,AwayBudget>};
type Broadcast=(event:{kind:"state";state:PublicXiangqiGameState}|{kind:"move";state:PublicXiangqiGameState;delta:XiangqiMoveDelta})=>void;
const iso=()=>new Date().toISOString();
const other=(c:XiangqiColor):XiangqiColor=>c==="red"?"black":"red";
const CHECKPOINT_EVERY_MOVE=4;
const FINISHED_TTL=30*60_000;
export class XiangqiGameManager{
  private games=new Map<string,Runtime>();
  private queues=new Map<string,Promise<unknown>>();
  private timer:NodeJS.Timeout;
  private evictions=new Map<string,NodeJS.Timeout>();
  constructor(private persistence:XiangqiPersistenceService,private broadcast:Broadcast){this.timer=setInterval(()=>{void this.checkTimeouts();},300);this.timer.unref();}
  private enqueue<T>(gameId:string,task:()=>Promise<T>):Promise<T>{const prev=this.queues.get(gameId)??Promise.resolve();const next=prev.catch(()=>undefined).then(task);const tracked=next.finally(()=>{if(this.queues.get(gameId)===tracked)this.queues.delete(gameId);});this.queues.set(gameId,tracked);return next;}
  async create(familyId:string,uidA:string,uidB:string,timeControl:XiangqiTimeControl,requestId?:string,options?:{testBotUid?:string|null;redUid?:string;blackUid?:string}){
    const id=randomUUID();const explicit=options?.redUid&&options?.blackUid&&new Set([options.redUid,options.blackUid]).size===2;const redUid=explicit?options!.redUid!:(Math.random()<.5?uidA:uidB);const blackUid=explicit?options!.blackUid!:(redUid===uidA?uidB:uidA);const now=iso();
    const game:PersistedXiangqiGame={id,familyId,redUid,blackUid,playerUids:[redUid,blackUid],status:"waiting",board:createInitialXiangqiState(),revision:1,redRemainingMs:timeControl.kind==="clocked"?timeControl.initialMs:null,blackRemainingMs:timeControl.kind==="clocked"?timeControl.initialMs:null,timeControl,result:null,finishReason:null,recentRequestIds:requestId?[requestId]:[],testBotUid:options?.testBotUid??null,isTestGame:!!options?.testBotUid,createdAt:now,startedAt:null,endedAt:null,updatedAt:now};
    await this.persistence.createWithLocks(game);const bot=options?.testBotUid;this.games.set(id,{game,turnStartedMono:null,connectedUids:new Set(bot?[bot]:[]),readyUids:new Set(bot?[bot]:[]),boardAwayByUid:new Map()});return this.publicState(this.games.get(id)!);
  }
  async restore(familyId:string,gameId:string){const existing=this.games.get(gameId);if(existing)return existing;const stored=await this.persistence.load(familyId,gameId);if(!stored)throw new XiangqiDomainError("XIANGQI_GAME_NOT_FOUND");if(stored.status==="active"){stored.status="paused";stored.revision+=1;stored.updatedAt=iso();await this.persistence.save(stored);}const bot=stored.testBotUid;const r:Runtime={game:stored,turnStartedMono:null,connectedUids:new Set(bot?[bot]:[]),readyUids:new Set(bot?[bot]:[]),boardAwayByUid:new Map()};this.games.set(gameId,r);return r;}
  async join(familyId:string,gameId:string,uid:string){return this.enqueue(gameId,async()=>{const r=await this.restore(familyId,gameId);this.assertPlayer(r,uid);r.connectedUids.add(uid);if(r.game.status==="paused"&&r.connectedUids.has(r.game.redUid)&&r.connectedUids.has(r.game.blackUid)){r.game.status="active";r.game.revision+=1;r.game.updatedAt=iso();r.turnStartedMono=r.game.timeControl.kind==="clocked"?performance.now():null;await this.persistence.save(r.game);const state=this.publicState(r);this.broadcast({kind:"state",state});return state;}return this.publicState(r);});}
  disconnect(gameId:string,uid:string){this.games.get(gameId)?.connectedUids.delete(uid);}
  async markReady(gameId:string,uid:string,requestId:string){return this.enqueue(gameId,async()=>{const r=this.requireRuntime(gameId);this.assertPlayer(r,uid);if(r.game.status==="finished")throw new XiangqiDomainError("XIANGQI_GAME_FINISHED");if(r.game.status==="active")return this.publicState(r);if(r.game.status!=="waiting")throw new XiangqiDomainError("XIANGQI_SERVER_RECOVERING");r.readyUids.add(uid);if(!(r.readyUids.has(r.game.redUid)&&r.readyUids.has(r.game.blackUid)))return this.publicState(r);r.game.status="active";r.game.startedAt=iso();r.game.updatedAt=iso();r.game.revision+=1;this.remember(r.game,requestId);r.turnStartedMono=r.game.timeControl.kind==="clocked"?performance.now():null;await this.persistence.save(r.game);const state=this.publicState(r);this.broadcast({kind:"state",state});return state;});}
  async state(gameId:string,uid:string){const r=this.requireRuntime(gameId);this.assertPlayer(r,uid);return this.publicState(r);}
  async setBoardVisible(gameId:string,uid:string,visible:boolean){return this.enqueue(gameId,async()=>{const r=this.requireRuntime(gameId);this.assertPlayer(r,uid);const expired=this.expiredTerminal(r);if(expired){if(expired.kind==="away")await this.finishByAway(r,expired.uid);else await this.finishByClock(r);this.broadcast({kind:"state",state:this.publicState(r)});return {visible,awayDeadlineAt:null,finished:true};}if(visible||r.game.status!=="active"||r.game.timeControl.kind!=="clocked"){r.boardAwayByUid.delete(uid);return {visible,awayDeadlineAt:null};}const existing=r.boardAwayByUid.get(uid);if(existing)return {visible:false,awayDeadlineAt:Date.now()+Math.max(0,existing.deadlineMono-performance.now())};const remaining=this.remainingForUid(r,uid);if(remaining==null)return {visible:false,awayDeadlineAt:null};const deadlineMono=performance.now()+remaining*.5;r.boardAwayByUid.set(uid,{deadlineMono,remainingAtLeaveMs:remaining});return {visible:false,awayDeadlineAt:Date.now()+remaining*.5};});}
  async move(gameId:string,uid:string,clientMoveId:string,expectedRevision:number,pieceId:string,to:{col:number;row:number}):Promise<XiangqiMoveAck>{return this.enqueue(gameId,async()=>{const r=this.requireRuntime(gameId);this.assertPlayer(r,uid);this.assertActive(r);if(r.game.recentRequestIds.includes(clientMoveId))return {clientMoveId,version:r.game.revision,duplicate:true};if(expectedRevision!==r.game.revision)throw new XiangqiDomainError("XIANGQI_STATE_CONFLICT");const color=r.game.redUid===uid?"red":"black";if(r.game.board.turn!==color)throw new XiangqiDomainError("XIANGQI_NOT_YOUR_TURN");const expired=this.expiredTerminal(r);if(expired){if(expired.kind==="away")await this.finishByAway(r,expired.uid);else await this.finishByClock(r);this.broadcast({kind:"state",state:this.publicState(r)});throw new XiangqiDomainError("XIANGQI_GAME_FINISHED");}
    this.consumeClock(r,color);const before=r.game.board;const after=playXiangqiMove(before,pieceId,to);if(after===before)throw new XiangqiDomainError("XIANGQI_ILLEGAL_MOVE");if(r.game.timeControl.kind==="clocked"){if(color==="red")r.game.redRemainingMs=(r.game.redRemainingMs??0)+r.game.timeControl.incrementMs;else r.game.blackRemainingMs=(r.game.blackRemainingMs??0)+r.game.timeControl.incrementMs;}r.game.board=after;r.game.revision+=1;r.game.updatedAt=iso();this.remember(r.game,clientMoveId);r.turnStartedMono=r.game.timeControl.kind==="clocked"?performance.now():null;if(after.gameOver){r.game.result=after.winner;r.game.finishReason=after.finishReason;r.game.status="finished";r.game.endedAt=iso();r.turnStartedMono=null;r.boardAwayByUid.clear();await this.persistence.finish(r.game);this.scheduleEviction(r);}else if((after.moveNumber-1)%CHECKPOINT_EVERY_MOVE===0)await this.persistence.save(r.game);const state=this.publicState(r);const delta:XiangqiMoveDelta={gameId,clientMoveId,version:state.revision,move:after.lastMove!,board:structuredClone(after),redRemainingMs:state.redRemainingMs,blackRemainingMs:state.blackRemainingMs,status:state.status,result:state.result,finishReason:state.finishReason,serverNowMs:state.serverNowMs,endedAt:state.endedAt};this.broadcast({kind:"move",state,delta});return {clientMoveId,version:state.revision};});}
  async resign(gameId:string,uid:string,requestId:string){return this.enqueue(gameId,async()=>{const r=this.requireRuntime(gameId);this.assertPlayer(r,uid);this.assertActive(r);if(r.game.recentRequestIds.includes(requestId))return this.publicState(r);const loser=r.game.redUid===uid?"red":"black";r.game.result=other(loser);r.game.finishReason="resignation";r.game.status="finished";r.game.endedAt=iso();r.game.revision+=1;r.game.updatedAt=iso();r.game.board={...r.game.board,winner:other(loser),gameOver:true};this.remember(r.game,requestId);r.turnStartedMono=null;r.boardAwayByUid.clear();await this.persistence.finish(r.game);this.scheduleEviction(r);const state=this.publicState(r);this.broadcast({kind:"state",state});return state;});}
  private requireRuntime(gameId:string){const r=this.games.get(gameId);if(!r)throw new XiangqiDomainError("XIANGQI_GAME_NOT_FOUND");return r;}
  private assertPlayer(r:Runtime,uid:string){if(uid!==r.game.redUid&&uid!==r.game.blackUid)throw new XiangqiDomainError("XIANGQI_NOT_PLAYER");}
  private assertActive(r:Runtime){if(r.game.status==="finished")throw new XiangqiDomainError("XIANGQI_GAME_FINISHED");if(r.game.status!=="active")throw new XiangqiDomainError("XIANGQI_SERVER_RECOVERING");}
  private remember(g:PersistedXiangqiGame,id:string){g.recentRequestIds=[...g.recentRequestIds.filter(x=>x!==id),id].slice(-24);}
  private consumeClock(r:Runtime,color:XiangqiColor){if(r.game.timeControl.kind!=="clocked"||r.turnStartedMono==null)return;const elapsed=Math.max(0,performance.now()-r.turnStartedMono);if(color==="red")r.game.redRemainingMs=Math.max(0,(r.game.redRemainingMs??0)-elapsed);else r.game.blackRemainingMs=Math.max(0,(r.game.blackRemainingMs??0)-elapsed);if((color==="red"?r.game.redRemainingMs:r.game.blackRemainingMs)===0)throw new XiangqiDomainError("XIANGQI_GAME_FINISHED");}
  private normalDeadline(r:Runtime){if(r.game.status!=="active"||r.game.timeControl.kind!=="clocked"||r.turnStartedMono==null)return null;const rem=r.game.board.turn==="red"?r.game.redRemainingMs:r.game.blackRemainingMs;return rem==null?null:r.turnStartedMono+rem;}
  private expiredTerminal(r:Runtime):{kind:"clock"}|{kind:"away";uid:string}|null{if(r.game.status!=="active")return null;const now=performance.now();const candidates:Array<{d:number;kind:"clock"|"away";uid?:string}>=[];const nd=this.normalDeadline(r);if(nd!=null&&now>=nd)candidates.push({d:nd,kind:"clock"});for(const [uid,a] of r.boardAwayByUid)if(now>=a.deadlineMono)candidates.push({d:a.deadlineMono,kind:"away",uid});candidates.sort((a,b)=>a.d-b.d);const x=candidates[0];return !x?null:x.kind==="away"&&x.uid?{kind:"away",uid:x.uid}:{kind:"clock"};}
  private remainingForUid(r:Runtime,uid:string){if(r.game.timeControl.kind!=="clocked")return null;const color=r.game.redUid===uid?"red":"black";let rem=color==="red"?r.game.redRemainingMs:r.game.blackRemainingMs;if(rem==null)return null;if(r.game.status==="active"&&r.turnStartedMono!=null&&r.game.board.turn===color)rem=Math.max(0,rem-(performance.now()-r.turnStartedMono));return rem;}
  private async finishByClock(r:Runtime){const loser=r.game.board.turn;const winner=other(loser);if(loser==="red")r.game.redRemainingMs=0;else r.game.blackRemainingMs=0;r.game.result=winner;r.game.finishReason="timeout";r.game.status="finished";r.game.endedAt=iso();r.game.updatedAt=iso();r.game.revision+=1;r.game.board={...r.game.board,winner,finishReason:"timeout",gameOver:true};r.turnStartedMono=null;r.boardAwayByUid.clear();await this.persistence.finish(r.game);this.scheduleEviction(r);}
  private async finishByAway(r:Runtime,uid:string){const loser=r.game.redUid===uid?"red":"black",winner=other(loser);r.game.result=winner;r.game.finishReason="away_timeout";r.game.status="finished";r.game.endedAt=iso();r.game.updatedAt=iso();r.game.revision+=1;r.game.board={...r.game.board,winner,gameOver:true};r.turnStartedMono=null;r.boardAwayByUid.clear();await this.persistence.finish(r.game);this.scheduleEviction(r);}
  private async checkTimeouts(){for(const [id,r] of this.games){const ex=this.expiredTerminal(r);if(!ex)continue;await this.enqueue(id,async()=>{const x=this.expiredTerminal(r);if(!x)return;if(x.kind==="away")await this.finishByAway(r,x.uid);else await this.finishByClock(r);this.broadcast({kind:"state",state:this.publicState(r)});});}}
  private scheduleEviction(r:Runtime){const old=this.evictions.get(r.game.id);if(old)clearTimeout(old);const t=setTimeout(()=>{if(this.games.get(r.game.id)===r)this.games.delete(r.game.id);this.evictions.delete(r.game.id);},FINISHED_TTL);t.unref();this.evictions.set(r.game.id,t);}
  private publicState(r:Runtime):PublicXiangqiGameState{let red=r.game.redRemainingMs,black=r.game.blackRemainingMs;if(r.game.status==="active"&&r.game.timeControl.kind==="clocked"&&r.turnStartedMono!=null){const elapsed=Math.max(0,performance.now()-r.turnStartedMono);if(r.game.board.turn==="red"&&red!=null)red=Math.max(0,red-elapsed);if(r.game.board.turn==="black"&&black!=null)black=Math.max(0,black-elapsed);}const {id,playerUids,recentRequestIds,updatedAt,...rest}=r.game;return {...rest,gameId:id,redRemainingMs:red,blackRemainingMs:black,board:structuredClone(r.game.board),serverNowMs:Date.now()};}
}
