import type { XiangqiBoardState, XiangqiColor, XiangqiMove, XiangqiPiece, XiangqiPieceType } from "./xiangqiTypes.js";
const BACK: XiangqiPieceType[]=["chariot","horse","elephant","advisor","general","advisor","elephant","horse","chariot"];
const VALUE:Record<XiangqiPieceType,number>={general:1000,chariot:9,cannon:5,horse:4,elephant:2,advisor:2,soldier:1};
const other=(c:XiangqiColor):XiangqiColor=>c==="red"?"black":"red";
const inside=(c:number,r:number)=>c>=0&&c<=8&&r>=0&&r<=9;
export const createInitialXiangqiState=():XiangqiBoardState=>({pieces:[
  ...BACK.map((type,col)=>({id:`b-back-${col}`,color:"black" as const,type,col,row:0})),
  {id:"b-cannon-1",color:"black",type:"cannon",col:1,row:2},{id:"b-cannon-7",color:"black",type:"cannon",col:7,row:2},
  ...[0,2,4,6,8].map((col,i)=>({id:`b-soldier-${i}`,color:"black" as const,type:"soldier" as const,col,row:3})),
  ...[0,2,4,6,8].map((col,i)=>({id:`r-soldier-${i}`,color:"red" as const,type:"soldier" as const,col,row:6})),
  {id:"r-cannon-1",color:"red",type:"cannon",col:1,row:7},{id:"r-cannon-7",color:"red",type:"cannon",col:7,row:7},
  ...BACK.map((type,col)=>({id:`r-back-${col}`,color:"red" as const,type,col,row:9})),
],turn:"red",moveNumber:1,lastMove:null,inCheck:null,winner:null,finishReason:null,gameOver:false});
const at=(ps:readonly XiangqiPiece[],c:number,r:number)=>ps.find(p=>p.col===c&&p.row===r);
const palace=(color:XiangqiColor,c:number,r:number)=>c>=3&&c<=5&&(color==="black"?(r>=0&&r<=2):(r>=7&&r<=9));
const elephantOk=(color:XiangqiColor,r:number)=>color==="black"?r<=4:r>=5;
const crossed=(color:XiangqiColor,r:number)=>color==="black"?r>=5:r<=4;
type Sq={col:number;row:number};
function push(out:Sq[],ps:readonly XiangqiPiece[],p:XiangqiPiece,c:number,r:number){ if(!inside(c,r))return; const t=at(ps,c,r); if(!t||t.color!==p.color)out.push({col:c,row:r}); }
function pseudo(ps:readonly XiangqiPiece[],p:XiangqiPiece):Sq[]{ const out:Sq[]=[]; const {col,row,color,type}=p;
 if(type==="general"){ for(const [dc,dr] of [[1,0],[-1,0],[0,1],[0,-1]] as const){const c=col+dc,r=row+dr;if(palace(color,c,r))push(out,ps,p,c,r);} const g=ps.find(x=>x.color!==color&&x.type==="general"); if(g&&g.col===col){let blocked=false;for(let r=Math.min(row,g.row)+1;r<Math.max(row,g.row);r++)if(at(ps,col,r)){blocked=true;break;}if(!blocked)out.push({col:g.col,row:g.row});} return out; }
 if(type==="advisor"){for(const [dc,dr] of [[1,1],[1,-1],[-1,1],[-1,-1]] as const){const c=col+dc,r=row+dr;if(palace(color,c,r))push(out,ps,p,c,r);}return out;}
 if(type==="elephant"){for(const [dc,dr] of [[2,2],[2,-2],[-2,2],[-2,-2]] as const){const c=col+dc,r=row+dr;if(!inside(c,r)||!elephantOk(color,r)||at(ps,col+dc/2,row+dr/2))continue;push(out,ps,p,c,r);}return out;}
 if(type==="horse"){for(const m of [{dc:2,dr:1,lc:1,lr:0},{dc:2,dr:-1,lc:1,lr:0},{dc:-2,dr:1,lc:-1,lr:0},{dc:-2,dr:-1,lc:-1,lr:0},{dc:1,dr:2,lc:0,lr:1},{dc:-1,dr:2,lc:0,lr:1},{dc:1,dr:-2,lc:0,lr:-1},{dc:-1,dr:-2,lc:0,lr:-1}]){if(at(ps,col+m.lc,row+m.lr))continue;push(out,ps,p,col+m.dc,row+m.dr);}return out;}
 if(type==="chariot"||type==="cannon"){for(const [dc,dr] of [[1,0],[-1,0],[0,1],[0,-1]] as const){let c=col+dc,r=row+dr,screen=false;while(inside(c,r)){const t=at(ps,c,r);if(type==="chariot"){if(!t)out.push({col:c,row:r});else{if(t.color!==color)out.push({col:c,row:r});break;}}else if(!screen){if(!t)out.push({col:c,row:r});else screen=true;}else if(t){if(t.color!==color)out.push({col:c,row:r});break;}c+=dc;r+=dr;}}return out;}
 if(type==="soldier"){const f=color==="red"?-1:1;push(out,ps,p,col,row+f);if(crossed(color,row)){push(out,ps,p,col-1,row);push(out,ps,p,col+1,row);}return out;} return out; }
function applyUnchecked(ps:readonly XiangqiPiece[],pieceId:string,to:Sq){const mover=ps.find(p=>p.id===pieceId); if(!mover)return {pieces:[...ps],captured:undefined as XiangqiPiece|undefined};const captured=at(ps,to.col,to.row);return {captured,pieces:ps.filter(p=>p.id!==captured?.id).map(p=>p.id===pieceId?{...p,col:to.col,row:to.row}:p)};}
export function isXiangqiInCheck(ps:readonly XiangqiPiece[],color:XiangqiColor){const g=ps.find(p=>p.color===color&&p.type==="general");if(!g)return true;return ps.filter(p=>p.color===other(color)).some(p=>pseudo(ps,p).some(t=>t.col===g.col&&t.row===g.row));}
export function legalForColor(state:Pick<XiangqiBoardState,"pieces"|"gameOver">,pieceId:string,color:XiangqiColor){if(state.gameOver)return [];const p=state.pieces.find(x=>x.id===pieceId);if(!p||p.color!==color)return [];return pseudo(state.pieces,p).filter(to=>!isXiangqiInCheck(applyUnchecked(state.pieces,p.id,to).pieces,p.color));}
export function allLegal(state:Pick<XiangqiBoardState,"pieces"|"turn"|"gameOver">):XiangqiMove[]{if(state.gameOver)return [];const out:XiangqiMove[]=[];for(const p of state.pieces.filter(x=>x.color===state.turn))for(const to of legalForColor(state,p.id,state.turn)){const target=at(state.pieces,to.col,to.row);out.push({pieceId:p.id,from:{col:p.col,row:p.row},to,...(target?{capturedId:target.id}:{})});}return out;}
export function playXiangqiMove(state:XiangqiBoardState,pieceId:string,to:Sq):XiangqiBoardState{if(state.gameOver)return state;const p=state.pieces.find(x=>x.id===pieceId);if(!p||p.color!==state.turn)return state;const legal=legalForColor(state,pieceId,state.turn);if(!legal.some(s=>s.col===to.col&&s.row===to.row))return state;const from={col:p.col,row:p.row};const a=applyUnchecked(state.pieces,pieceId,to);const next=other(state.turn);const move:XiangqiMove={pieceId,from,to,...(a.captured?{capturedId:a.captured.id}:{})};if(a.captured?.type==="general")return {...state,pieces:a.pieces,lastMove:move,moveNumber:state.moveNumber+1,inCheck:null,winner:state.turn,finishReason:"general_captured",gameOver:true};const probe:XiangqiBoardState={...state,pieces:a.pieces,turn:next,moveNumber:state.moveNumber+1,lastMove:move,inCheck:isXiangqiInCheck(a.pieces,next)?next:null,winner:null,finishReason:null,gameOver:false};if(allLegal(probe).length===0)return {...probe,winner:state.turn,finishReason:probe.inCheck?"checkmate":"stalemate",gameOver:true};return probe;}
export function chooseBotPlan(state:XiangqiBoardState,color:XiangqiColor){if(state.gameOver||state.turn!==color)return null;const scored=allLegal(state).map(move=>{const cap=move.capturedId?state.pieces.find(p=>p.id===move.capturedId):null;const after=playXiangqiMove(state,move.pieceId,move.to);const givesCheck=after.inCheck===other(color);let score=cap?VALUE[cap.type]*100:0;if(after.gameOver&&after.winner===color)score+=100000;else if(givesCheck)score+=35;score+=Math.random();return {move,score,givesCheck};}).sort((a,b)=>b.score-a.score);return scored[0]??null;}
