import { where } from "firebase/firestore";
import { useState } from "react";
import { useWebAuth } from "../context/WebAuthContext";
import { useWebFamily } from "../context/WebFamilyContext";
import { useWebCollection } from "../hooks/useWebCollection";
import { useWebDocument } from "../hooks/useWebDocument";
import { approveWebJoin, createWebFamily, rejectWebJoin, requestWebFamilyJoin, updateWebProfile } from "../services/webFamilyService";
import { FormRow, InlineNotice } from "./WebOverlay";

export function WebFamilyGateway() {
  const auth=useWebAuth(); const family=useWebFamily(); const [mode,setMode]=useState<"create"|"join">("create"); const [name,setName]=useState(""); const [code,setCode]=useState(""); const [message,setMessage]=useState(""); const [status,setStatus]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const run=async()=>{if(!auth.user)return;setBusy(true);setStatus(null);try{if(mode==="create"){const created=await createWebFamily(auth.user.uid,name,family.profile||{uid:auth.user.uid,displayName:auth.user.displayName||"Thành viên"});setStatus(`Đã tạo ${created.familyName}. Mã Nhà: ${created.familyCode}`);}else{const request=await requestWebFamilyJoin(auth.user.uid,code,family.profile||{uid:auth.user.uid,displayName:auth.user.displayName||"Thành viên"},message);setStatus(`Yêu cầu vào ${request.familyName} đã được gửi. Khi admin duyệt, Nhà sẽ xuất hiện tự động.`);}}catch(e){setStatus(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
  return <div style={gateway}><div style={flower}>🏡</div><h1 style={{margin:0}}>Mở cửa Nhà Mình</h1><p style={copy}>Bạn có thể tạo một mái nhà mới hoặc xin tham gia bằng mã Nhà ngay trên iPhone, iPad hay web.</p><div style={switcher}><button className={`bloom-btn ${mode==="create"?"primary":"secondary"}`} onClick={()=>setMode("create")}>Tạo Nhà</button><button className={`bloom-btn ${mode==="join"?"primary":"secondary"}`} onClick={()=>setMode("join")}>Xin vào Nhà</button></div><div style={panel}>{mode==="create"?<FormRow label="Tên mái nhà"><input className="bloom-field" value={name} onChange={e=>setName(e.target.value)} placeholder="Ví dụ: Nhà của chúng mình"/></FormRow>:<><FormRow label="Mã Nhà hoặc Family ID"><input className="bloom-field" value={code} onChange={e=>setCode(e.target.value)} placeholder="nhaminh-xxxx" autoCapitalize="none"/></FormRow><FormRow label="Lời nhắn"><textarea className="bloom-field" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Con là…" rows={3}/></FormRow></>}<button className="bloom-btn primary" style={{width:"100%"}} disabled={busy} onClick={()=>void run()}>{busy?"Bloom đang xử lý…":mode==="create"?"Tạo mái nhà":"Gửi yêu cầu"}</button>{status?<InlineNotice tone={status.startsWith("Đã")||status.includes("được gửi")?"success":"warning"}>{status}</InlineNotice>:null}</div><button className="bloom-btn secondary" onClick={()=>void auth.logout()}>Đăng xuất</button></div>;
}

export function WebFamilyManager() {
 const auth=useWebAuth(); const family=useWebFamily(); const [section,setSection]=useState<"profile"|"family"|"join">("profile"); const [displayName,setDisplayName]=useState(family.profile?.displayName||auth.user?.displayName||""); const [shortName,setShortName]=useState(family.profile?.shortName||""); const [color,setColor]=useState(family.profile?.color||"#E98AA6"); const [phoneNumber,setPhoneNumber]=useState(family.profile?.phoneNumber||auth.user?.phoneNumber||""); const [birthDate,setBirthDate]=useState(family.profile?.birthDate||""); const [gender,setGender]=useState<"male"|"female"|"other">(family.profile?.gender||"other"); const [currentLocation,setCurrentLocation]=useState(family.profile?.currentLocation||""); const [bio,setBio]=useState(family.profile?.bio||""); const [bloodType,setBloodType]=useState(family.profile?.bloodType||"other"); const [interests,setInterests]=useState<string[]>(family.profile?.interests||[]); const [avatar,setAvatar]=useState<File|null>(null); const [familyName,setFamilyName]=useState(""); const [joinCode,setJoinCode]=useState(""); const [joinMessage,setJoinMessage]=useState(""); const [status,setStatus]=useState<string|null>(null); const [busy,setBusy]=useState(false);
 const activeRole=family.memberships.find(x=>x.familyId===family.activeFamilyId)?.role; const pendingConstraints=[where("status","==","pending")] as any; const pending=useWebCollection<any>(activeRole==="admin"&&family.activeFamilyId?`families/${family.activeFamilyId}/joinRequests`:null,pendingConstraints); const familyDoc=useWebDocument<any>(family.activeFamilyId?`families/${family.activeFamilyId}`:null);
 const execute=async(action:()=>Promise<any>,success:string)=>{setBusy(true);setStatus(null);try{await action();setStatus(success);}catch(e){setStatus(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
 return <div><div style={tabs}>{([['profile','Hồ sơ'],['family','Mái nhà'],['join','Tham gia']] as const).map(([id,label])=><button key={id} className={`bloom-btn ${section===id?'primary':'secondary'}`} onClick={()=>setSection(id)}>{label}</button>)}</div>
 {section==="profile"?<div style={sectionBox}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><FormRow label="Tên hiển thị"><input className="bloom-field" value={displayName} onChange={e=>setDisplayName(e.target.value)}/></FormRow><FormRow label="Tên ngắn"><input className="bloom-field" value={shortName} onChange={e=>setShortName(e.target.value)}/></FormRow><FormRow label="Số điện thoại"><input className="bloom-field" inputMode="tel" value={phoneNumber} onChange={e=>setPhoneNumber(e.target.value)}/></FormRow><FormRow label="Ngày sinh"><input className="bloom-field" type="date" value={birthDate?.slice(0,10)||""} onChange={e=>setBirthDate(e.target.value)}/></FormRow><FormRow label="Giới tính"><select className="bloom-field" value={gender} onChange={e=>setGender(e.target.value as any)}><option value="other">Khác / không muốn nêu</option><option value="female">Nữ</option><option value="male">Nam</option></select></FormRow><FormRow label="Nhóm máu"><select className="bloom-field" value={bloodType} onChange={e=>setBloodType(e.target.value)}>{["other","A+","A-","B+","B-","AB+","AB-","O+","O-"].map(x=><option key={x} value={x}>{x==="other"?"Chưa chọn":x}</option>)}</select></FormRow><FormRow label="Nơi đang sống"><input className="bloom-field" value={currentLocation} onChange={e=>setCurrentLocation(e.target.value)}/></FormRow><FormRow label="Màu Bloom"><input type="color" className="bloom-field" value={color} onChange={e=>setColor(e.target.value)}/></FormRow></div><FormRow label="Giới thiệu"><textarea className="bloom-field bloom-textarea" rows={3} value={bio} onChange={e=>setBio(e.target.value)} placeholder="Một điều nhỏ về bạn…"/></FormRow><FormRow label="Sở thích"><div style={{display:"flex",flexWrap:"wrap",gap:6}}>{[["music","🎵 Âm nhạc"],["reading","📚 Đọc sách"],["cooking","🍳 Nấu ăn"],["travel","✈️ Du lịch"],["plant","🌿 Cây cối"],["photo","📸 Nhiếp ảnh"]].map(([id,label])=>{const active=interests.includes(id);return <button type="button" key={id} className="bloom-chip" data-active={active} onClick={()=>setInterests(active?interests.filter(x=>x!==id):[...interests,id])}>{label}</button>})}</div></FormRow><FormRow label="Ảnh đại diện"><input className="bloom-field" type="file" accept="image/*" onChange={e=>setAvatar(e.target.files?.[0]||null)}/></FormRow><button className="bloom-btn primary" disabled={busy||!auth.user||!displayName.trim()} onClick={()=>auth.user&&void execute(()=>updateWebProfile(auth.user!.uid,family.activeFamilyId,{displayName,shortName,color,phoneNumber,birthDate,gender,currentLocation,bio,bloodType,interests,avatarFile:avatar}),"Đã cập nhật hồ sơ.")}>Lưu hồ sơ</button></div>:null}
 {section==="family"?<div style={sectionBox}><div style={houseCard}><b>{family.activeFamily?.familyName}</b><span>Mã Nhà: <strong>{familyDoc.data?.familyCode||"Chưa có mã"}</strong></span><span>{family.members.length} thành viên · vai trò {activeRole||"member"}</span></div><FormRow label="Tạo thêm mái nhà"><input className="bloom-field" value={familyName} onChange={e=>setFamilyName(e.target.value)} placeholder="Tên Nhà mới"/></FormRow><button className="bloom-btn primary" disabled={busy||!auth.user} onClick={()=>auth.user&&void execute(()=>createWebFamily(auth.user!.uid,familyName,family.profile||{}),"Đã tạo mái nhà mới." )}>Tạo Nhà mới</button>{activeRole==="admin"?<div style={{marginTop:18}}><b>Yêu cầu đang chờ ({pending.items.length})</b><div style={{display:'grid',gap:8,marginTop:8}}>{pending.items.map(r=><div key={r.id} style={requestRow}><div><b>{r.applicant?.displayName||"Thành viên"}</b><div style={small}>{r.message||"Muốn tham gia Nhà Mình"}</div></div><div style={{display:'flex',gap:6}}><button className="bloom-btn secondary" onClick={()=>auth.user&&void execute(()=>rejectWebJoin(family.activeFamilyId!,r,auth.user!.uid),"Đã từ chối yêu cầu.")}>Từ chối</button><button className="bloom-btn primary" onClick={()=>auth.user&&void execute(()=>approveWebJoin(family.activeFamilyId!,r,auth.user!.uid),"Đã thêm thành viên vào Nhà.")}>Duyệt</button></div></div>)}</div></div>:null}</div>:null}
 {section==="join"?<div style={sectionBox}><FormRow label="Mã Nhà hoặc Family ID"><input className="bloom-field" value={joinCode} onChange={e=>setJoinCode(e.target.value)} autoCapitalize="none"/></FormRow><FormRow label="Lời nhắn"><textarea className="bloom-field" rows={3} value={joinMessage} onChange={e=>setJoinMessage(e.target.value)}/></FormRow><button className="bloom-btn primary" disabled={busy||!auth.user} onClick={()=>auth.user&&void execute(()=>requestWebFamilyJoin(auth.user!.uid,joinCode,family.profile||{},joinMessage),"Đã gửi yêu cầu tham gia.")}>Gửi yêu cầu</button></div>:null}
 {status?<InlineNotice tone={status.startsWith("Đã")?"success":"warning"}>{status}</InlineNotice>:null}</div>;
}
const gateway:React.CSSProperties={minHeight:"100dvh",display:"grid",placeItems:"center",alignContent:"center",gap:14,padding:24,fontFamily:"Inter,system-ui,sans-serif",color:"#5c444d",background:"#fffaf8"};const flower:React.CSSProperties={fontSize:46};const copy:React.CSSProperties={maxWidth:520,textAlign:"center",color:"#8b727b",lineHeight:1.6,margin:"0 0 4px"};const switcher:React.CSSProperties={display:"flex",gap:8};const panel:React.CSSProperties={width:"min(100%,520px)",background:"white",border:"1px solid #f0dfe5",borderRadius:22,padding:18,boxShadow:"0 14px 35px rgba(115,73,88,.08)"};const tabs:React.CSSProperties={display:"flex",gap:7,flexWrap:"wrap",marginBottom:14};const sectionBox:React.CSSProperties={display:"grid",gap:10};const houseCard:React.CSSProperties={display:"grid",gap:4,background:"#fff5f7",borderRadius:16,padding:14,fontSize:12,color:"#806970"};const requestRow:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,padding:10,borderRadius:14,background:"#fff8fa"};const small:React.CSSProperties={fontSize:11,color:"#9a838b",marginTop:3};
