export type ErrorCategory =
  | "AUTH"
  | "PROFILE"
  | "FAMILY"
  | "EVENT"
  | "MOMENT"
  | "REACTION"
  | "COMMENT"
  | "MEDIA"
  | "GRAPH"
  | "PERSON"
  | "RELATIONSHIP"
  | "NETWORK"
  | "VALIDATION"
  | "FIREBASE"
  | "SYSTEM"
  | "UNKNOWN";

export type AppErrorCode =
  | "VALIDATION_REQUIRED" | "VALIDATION_EMAIL" | "VALIDATION_PASSWORD_SHORT" | "VALIDATION_PASSWORD_MISMATCH"
  | "GOOGLE_CLIENT_ID_MISSING" | "AUTH_GOOGLE_CANCELLED" | "AUTH_GOOGLE_IN_PROGRESS" | "AUTH_GOOGLE_PLAY_SERVICES" | "AUTH_GOOGLE_FAILED"
  | "AUTH_INVALID_PHONE" | "AUTH_INVALID_CODE" | "AUTH_CODE_EXPIRED" | "AUTH_TOO_MANY_REQUESTS"
  | "PROFILE_NOT_FOUND" | "PROFILE_SAVE_FAILED"
  | "MEDIA_CONFIG_MISSING" | "MEDIA_UPLOAD_FAILED" | "MEDIA_FILE_TOO_LARGE" | "MEDIA_ATTACH_FAILED" | "MEDIA_CLEANUP_PENDING" | "FAMILY_CONTEXT_REQUIRED"
  | "FAMILY_ID_REQUIRED" | "FAMILY_NOT_FOUND" | "FAMILY_CODE_GENERATION_FAILED" | "ALREADY_FAMILY_MEMBER" | "JOIN_REQUEST_PENDING" | "JOIN_REQUEST_NOT_PENDING" | "USER_PROFILE_NOT_FOUND"
  | "FAMILY_MEMBERSHIP_REQUIRED"
  | "EVENT_INVALID_DATE" | "EVENT_DATE_IN_PAST" | "EVENT_TITLE_REQUIRED" | "EVENT_PARTICIPANTS_REQUIRED" | "EVENT_PARTICIPANT_NOT_MEMBER" | "EVENT_NOT_FOUND" | "EVENT_NOT_OWNER" | "EVENT_MODERATION_DENIED"
  | "COMMENT_EMPTY" | "MOMENT_NOT_FOUND" | "MOMENT_NOT_OWNER" | "MOMENT_MODERATION_DENIED"
  | "GRAPH_PERMISSION_DENIED" | "GRAPH_FAMILY_MISMATCH" | "GRAPH_BACKEND_UNAVAILABLE"
  | "PERSON_NOT_FOUND" | "PERSON_INVALID_DATA" | "PERSON_ALREADY_LINKED" | "PERSON_HAS_RELATIONSHIPS"
  | "LINKED_UID_NOT_MEMBER" | "UID_ALREADY_LINKED"
  | "RELATIONSHIP_NOT_FOUND" | "RELATIONSHIP_INVALID" | "RELATIONSHIP_DUPLICATE" | "RELATIONSHIP_SELF_REFERENCE" | "RELATIONSHIP_PARENT_CYCLE"
  | "NETWORK_UNAVAILABLE" | "UNKNOWN";

export class AppError extends Error {
  readonly code: AppErrorCode;
  readonly category: ErrorCategory;
  readonly retryable: boolean;
  readonly cause?: unknown;

  constructor(code: AppErrorCode, category: ErrorCategory, message?: string, options?: { retryable?: boolean; cause?: unknown }) {
    super(message ?? code);
    this.name = "AppError";
    this.code = code;
    this.category = category;
    this.retryable = options?.retryable ?? false;
    this.cause = options?.cause;
  }
}
