import { Ionicons } from "@expo/vector-icons";
import { Image } from "expo-image";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenContainer } from "../components/layout/ScreenContainer";
import { BloomStickyHeader } from "../components/ui/BloomPageComponents";
import { COLORS } from "../constants/theme";
import { useAuth } from "../context/AuthContext";
import { memoryBookService } from "../services/memoryBookService";
import type { MomentPost } from "../types/moments";
import type { MemoryBookScope } from "../types/memoryBook";

export default function MemoryBookScreen() {
  const router = useRouter(); const params = useLocalSearchParams<{ scope?: string; personId?: string; personName?: string }>();
  const { activeFamilyId, families } = useAuth(); const scope: MemoryBookScope = params.scope === "person" ? "person" : "family";
  const personId = typeof params.personId === "string" ? params.personId : null; const personName = typeof params.personName === "string" ? params.personName : "một người thân";
  const familyName = families.find((x) => x.familyId === activeFamilyId)?.familyName || "Gia đình";
  const [source, setSource] = useState<MomentPost[]>([]); const [selected, setSelected] = useState<string[]>([]); const [title, setTitle] = useState(scope === "person" ? `Câu chuyện của ${personName}` : `Kỷ yếu ${familyName}`);
  const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { let live = true; if (!activeFamilyId) return; setLoading(true); memoryBookService.loadSourceMoments(activeFamilyId, scope, personId, 120).then((items) => { if (!live) return; setSource(items); setSelected(items.slice(0, 40).map((x) => x.id)); }).finally(() => live && setLoading(false)); return () => { live = false; }; }, [activeFamilyId, personId, scope]);
  const chosen = useMemo(() => selected.map((id) => source.find((x) => x.id === id)).filter((x): x is MomentPost => !!x), [selected, source]);
  const toggle = (id: string) => setSelected((old) => old.includes(id) ? old.filter((x) => x !== id) : [...old, id]);
  const move = (index: number, delta: number) => setSelected((old) => { const next = [...old]; const target = index + delta; if (target < 0 || target >= next.length) return old; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const save = async () => { if (!activeFamilyId) return; setSaving(true); try { await memoryBookService.save({ familyId: activeFamilyId, scope, personId, title: title.trim() || "Kỷ yếu Bloom", subtitle: scope === "person" ? `Những mảnh ký ức của ${personName}` : `Những điều ${familyName} muốn giữ lại`, coverMomentId: selected[0] || null, momentIds: selected }); setSaved(true); setEditing(false); } finally { setSaving(false); } };
  const data = editing ? source : chosen;
  return <ScreenContainer>
    <BloomStickyHeader title="Kỷ yếu Bloom 📖" subtitle={scope === "person" ? "Câu chuyện một người" : "Chuyện của nhà mình"} onBack={() => router.back()} />
    <View style={styles.toolbar}><Pressable onPress={() => setEditing((v) => !v)} style={styles.tool}><Ionicons name={editing ? "book-outline" : "create-outline"} size={18} color={COLORS.primaryText}/><Text style={styles.toolText}>{editing ? "Xem sách" : "Biên tập"}</Text></Pressable><Pressable disabled={saving} onPress={save} style={[styles.save, saving && {opacity:.6}]}><Text style={styles.saveText}>{saving ? "Đang lưu…" : saved ? "Đã lưu ✓" : "Lưu kỷ yếu"}</Text></Pressable></View>
    {loading ? <View style={styles.loading}><ActivityIndicator color={COLORS.primary}/><Text style={styles.muted}>Bloom đang gom những trang đáng nhớ…</Text></View> :
    <FlatList data={data} keyExtractor={(x) => x.id} initialNumToRender={6} maxToRenderPerBatch={6} windowSize={5} contentContainerStyle={styles.list} ListHeaderComponent={<View style={styles.cover}><Text style={styles.coverEyebrow}>{scope === "person" ? "CÂU CHUYỆN MỘT NGƯỜI" : "CHUYỆN CỦA NHÀ MÌNH"}</Text>{editing ? <TextInput value={title} onChangeText={setTitle} style={styles.titleInput} maxLength={80}/> : <Text style={styles.coverTitle}>{title}</Text>}<Text style={styles.coverMeta}>{selected.length} kỷ niệm được chọn · bạn có thể sắp xếp lại bất cứ lúc nào</Text></View>} ListEmptyComponent={<View style={styles.empty}><Ionicons name="book-outline" size={30} color={COLORS.primary}/><Text style={styles.emptyTitle}>Cuốn sách đang chờ trang đầu tiên</Text><Text style={styles.muted}>Hãy tạo hoặc gắn kỷ niệm vào dòng thời gian trước nhé.</Text></View>} renderItem={({item,index}) => { const media=item.media[0]; const isSelected=selected.includes(item.id); return <View style={[styles.page,!isSelected&&editing&&styles.unselected]}>{media?.secureUrl ? <Image source={{uri:media.thumbnailUrl||media.secureUrl}} style={styles.heroImage} contentFit="cover" cachePolicy="memory-disk"/>:<View style={styles.noImage}><Ionicons name="flower-outline" size={28} color={COLORS.primary}/></View>}<Text style={styles.date}>{new Date(item.createdAt).toLocaleDateString("vi-VN",{day:"2-digit",month:"long",year:"numeric"})}</Text><Text style={styles.pageTitle}>{item.caption||"Một ngày đáng nhớ"}</Text><Text style={styles.author}>{item.authorName}{item.media.length ? ` · ${item.media.length} ảnh/video` : ""}</Text>{editing&&<View style={styles.editRow}><Pressable onPress={()=>toggle(item.id)} style={[styles.select,isSelected&&styles.selectOn]}><Ionicons name={isSelected?"checkmark":"add"} size={16} color={isSelected?COLORS.white:COLORS.primaryText}/><Text style={[styles.selectText,isSelected&&{color:COLORS.white}]}>{isSelected?"Trong sách":"Thêm"}</Text></Pressable>{isSelected&&<><Pressable onPress={()=>move(selected.indexOf(item.id),-1)} style={styles.round}><Ionicons name="arrow-up" size={16} color={COLORS.primaryText}/></Pressable><Pressable onPress={()=>move(selected.indexOf(item.id),1)} style={styles.round}><Ionicons name="arrow-down" size={16} color={COLORS.primaryText}/></Pressable></>}</View>}</View>; }} />}
  </ScreenContainer>;
}
const styles=StyleSheet.create({toolbar:{flexDirection:"row",gap:12,marginBottom:12},tool:{flex:1,minHeight:46,borderRadius:16,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.white,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7},toolText:{color:COLORS.primaryText,fontWeight:"900"},save:{flex:1,minHeight:46,borderRadius:16,backgroundColor:COLORS.primary,alignItems:"center",justifyContent:"center"},saveText:{color:COLORS.white,fontWeight:"900"},loading:{paddingVertical:60,alignItems:"center",gap:10},list:{paddingBottom:40},cover:{minHeight:220,borderRadius:30,backgroundColor:COLORS.white,borderWidth:1,borderColor:COLORS.border,padding:24,justifyContent:"flex-end",marginBottom:18},coverEyebrow:{color:COLORS.primary,fontSize:10,fontWeight:"900",letterSpacing:1},coverTitle:{marginTop:8,color:COLORS.primaryText,fontSize:30,lineHeight:36,fontWeight:"900"},titleInput:{marginTop:10,color:COLORS.primaryText,fontSize:24,fontWeight:"900",borderWidth:1.5,borderColor:COLORS.inputBorder,backgroundColor:COLORS.white,borderRadius:16,paddingHorizontal:14,paddingVertical:10},coverMeta:{marginTop:10,color:COLORS.secondaryText,fontSize:11.5,lineHeight:17},page:{backgroundColor:COLORS.white,borderRadius:28,borderWidth:1,borderColor:COLORS.border,padding:14,marginBottom:16},unselected:{opacity:.58},heroImage:{width:"100%",aspectRatio:1.45,borderRadius:20,backgroundColor:COLORS.surfaceSoft},noImage:{height:130,borderRadius:20,backgroundColor:COLORS.surfaceSoft,alignItems:"center",justifyContent:"center"},date:{marginTop:14,color:COLORS.primary,fontSize:10,fontWeight:"900",textTransform:"uppercase"},pageTitle:{marginTop:6,color:COLORS.primaryText,fontSize:20,lineHeight:27,fontWeight:"900"},author:{marginTop:7,color:COLORS.secondaryText,fontSize:11.5,fontWeight:"600"},editRow:{marginTop:14,flexDirection:"row",gap:12,alignItems:"center"},select:{minHeight:38,borderRadius:14,paddingHorizontal:12,borderWidth:1,borderColor:COLORS.border,flexDirection:"row",alignItems:"center",gap:5},selectOn:{backgroundColor:COLORS.primary,borderColor:COLORS.primary},selectText:{color:COLORS.primaryText,fontSize:11,fontWeight:"900"},round:{width:38,height:38,borderRadius:14,backgroundColor:COLORS.surfaceSoft,alignItems:"center",justifyContent:"center"},empty:{paddingVertical:60,alignItems:"center",gap:8},emptyTitle:{color:COLORS.primaryText,fontSize:16,fontWeight:"900"},muted:{color:COLORS.secondaryText,fontSize:11.5,textAlign:"center"}});
