import { limit, where } from "firebase/firestore";
import { useEffect, useMemo, useState } from "react";
import { GAME_COPY, getBingoCell } from "../../data/games/homeGameQuestionBank";
import { formatHomeGameDeadline, getHomeGamePlayWindow } from "../../services/home/homeGamePolicy";
import type { HomeGameResponse, HomeGameSecret, HomeGameSession, HomeGameType } from "../../types/homeLiving";
import { useWebAuth } from "../context/WebAuthContext";
import { useWebFamily } from "../context/WebFamilyContext";
import { useWebCollection } from "../hooks/useWebCollection";
import { useWebDocument } from "../hooks/useWebDocument";
import { WebCard } from "../components/WebPrimitives";
import { InlineNotice, WebModal } from "../components/WebOverlay";
import { createWebHomeGame, getWebHomeGameSecret, submitWebHomeGameResponse, submitWebTruthStatements } from "../services/webHomeGameService";

const TYPES:HomeGameType[]=["know_each_other","guess_person","memory_owner","truth_lie","story_chain","family_bingo"];
export function WebFamilyMiniGames(){
 const auth=useWebAuth();const family=useWebFamily();const uid=auth.user?.uid||"";const name=family.profile?.displayName||auth.user?.displayName||"Thành viên";const constraints=useMemo(()=>uid?[where("participantUids","array-contains",uid),limit(80)]:[],[uid]);const sessions=useWebCollection<HomeGameSession>(family.activeFamilyId&&uid?`families/${family.activeFamilyId}/homeGameSessions`:null,constraints);const [selected,setSelected]=useState<HomeGameSession|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);const windowInfo=getHomeGamePlayWindow();
 const create=async(type:HomeGameType)=>{if(!family.activeFamilyId||!uid)return;setBusy(true);setMessage(null);try{const id=await createWebHomeGame({familyId:family.activeFamilyId,creatorUid:uid,creatorName:name,gameType:type,members:family.members});setMessage("Đã mở một lượt chơi mới cho cả nhà.");const found=sessions.items.find(x=>x.id===id);if(found)setSelected(found);}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
 return <div style={{display:"grid",gap:14}}><div className="bloom-card-grid">{TYPES.map(type=>{const m=GAME_COPY[type];return <button key={type} style={{...gameTypeCard,background:m.tone}} disabled={busy||!windowInfo.canCreate} onClick={()=>void create(type)}><span style={gameIcon}>{iconFor(type)}</span><div><b>{m.title}</b><div style={small}>{m.short}</div><div style={micro}>{m.minutes}</div></div><span style={{marginLeft:"auto"}}>＋</span></button>})}</div>{!windowInfo.canCreate?<InlineNotice tone="warning">{windowInfo.message}</InlineNotice>:null}{message?<InlineNotice tone={message.startsWith("Đã")?"success":"warning"}>{message}</InlineNotice>:null}<div><b style={{fontSize:14}}>Các lượt đang có</b><div style={{display:"grid",gap:8,marginTop:8}}>{sessions.items.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).map(s=><button key={s.id} style={sessionRow} onClick={()=>setSelected(s)}><span style={{fontSize:24}}>{iconFor(s.gameType)}</span><div style={{minWidth:0,textAlign:"left"}}><b>{s.title}</b><div style={small}>{s.submittedUids?.length||0}/{s.participantUids?.length||0} đã tham gia · {s.endsAtMs?`đến ${formatHomeGameDeadline(s.endsAtMs)}`:"đang chơi"}</div></div><span style={{marginLeft:"auto"}}>›</span></button>)}</div></div><WebModal open={!!selected} onClose={()=>setSelected(null)} title={selected?.title||"Trò chơi Nhà Mình"} sheet>{selected&&family.activeFamilyId?<MiniGameDetail session={selected} familyId={family.activeFamilyId} uid={uid} name={name} members={family.members}/>:null}</WebModal></div>;
}

function MiniGameDetail({session:initial,familyId,uid,name,members}:{session:HomeGameSession;familyId:string;uid:string;name:string;members:any[]}){
 const live=useWebDocument<HomeGameSession>(`families/${familyId}/homeGameSessions/${initial.id}`);const session=live.data||initial;const effectiveRevealed=session.status!=="playing"||!!(session.endsAtMs&&Date.now()>=session.endsAtMs);const publicQ=useMemo(()=>effectiveRevealed?[]:[where("public","==",true),limit(60)],[effectiveRevealed]);const responses=useWebCollection<HomeGameResponse>(`${`families/${familyId}/homeGameSessions/${session.id}`}/responses`,publicQ);const mine=useWebDocument<HomeGameResponse>(`families/${familyId}/homeGameSessions/${session.id}/responses/${uid}`);const [secret,setSecret]=useState<HomeGameSecret|null>(null);const [answers,setAnswers]=useState<string[]>(()=>session.prompts.map(()=>""));const [guess,setGuess]=useState<string>("");const [truth,setTruth]=useState(["","",""]);const [lie,setLie]=useState<number|null>(null);const [choice,setChoice]=useState<number|null>(null);const [story,setStory]=useState("");const [bingo,setBingo]=useState<string[]>(mine.data?.selectedIds||[]);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const subjectResponse=responses.items.find(r=>r.uid===session.subjectUid)||null;
 useEffect(()=>{if(effectiveRevealed||session.createdByUid===uid||session.subjectUid===uid)void getWebHomeGameSecret(familyId,session.id).then(setSecret);},[effectiveRevealed,familyId,session.createdByUid,session.id,session.subjectUid,uid]);useEffect(()=>{if(mine.data?.selectedIds)setBingo(mine.data.selectedIds)},[mine.data?.selectedIds?.join("|")]);
 const submit=async(payload:any)=>{setBusy(true);setError(null);try{await submitWebHomeGameResponse({familyId,session,uid,displayName:name,...payload});}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
 const renderChoices=(label:string)=><div style={stack}><b>{label}</b>{session.prompts.map((p,i)=><div key={p.id} style={question}><div style={category}>{p.category}</div><b>{p.prompt}</b><div style={optionGrid}>{p.options.map(o=><button className="bloom-chip" data-active={answers[i]===o} key={o} onClick={()=>setAnswers(a=>a.map((v,j)=>j===i?o:v))}>{o}</button>)}</div></div>)}<button className="bloom-btn primary" disabled={busy||answers.some(x=>!x)} onClick={()=>void submit({answers})}>Gửi câu trả lời</button></div>;
 const memberGuess=(label:string)=><div style={stack}><b>{label}</b><div style={optionGrid}>{members.filter(m=>session.participantUids.includes(m.uid)).map(m=><button className="bloom-chip" data-active={guess===m.uid} key={m.uid} onClick={()=>setGuess(m.uid)}>{m.displayName||m.shortName||"Thành viên"}</button>)}</div><button className="bloom-btn primary" disabled={!guess||busy} onClick={()=>void submit({guessUid:guess,guessName:members.find(m=>m.uid===guess)?.displayName||"Thành viên"})}>Chốt lựa chọn</button></div>;
 let content:React.ReactNode=null;
 if(session.gameType==="know_each_other"){if(effectiveRevealed){const rows=responses.items;const truthRow=rows.find(r=>r.uid===session.subjectUid);content=<div style={stack}><b>Đáp án của {session.subjectName}</b>{session.prompts.map((p,i)=><div style={resultLine} key={p.id}><span>{p.prompt}</span><strong>{truthRow?.answers[i]||"—"}</strong></div>)}</div>}else content=mine.data?<Done ends={session.endsAtMs}/>:renderChoices(session.subjectUid===uid?"Trả lời thật về bạn":`Bạn nghĩ ${session.subjectName} sẽ chọn gì?`)}
 if(session.gameType==="guess_person"){if(effectiveRevealed)content=<Reveal big={secret?.subjectName||session.subjectName||"Một người thân"} sub="Người bí mật của ván"/>;else if(session.subjectUid===uid)content=mine.data?<Done ends={session.endsAtMs}/>:renderChoices("Bạn đang là người bí mật · tạo 3 manh mối");else content=!subjectResponse?<Waiting text="Người bí mật đang chuẩn bị ba manh mối…"/>:mine.data?<Done ends={session.endsAtMs}/>:<div style={stack}>{session.prompts.map((p,i)=><div style={resultLine} key={p.id}><span>{p.prompt}</span><strong>{subjectResponse.answers[i]||"…"}</strong></div>)}{memberGuess("Bạn nghĩ đó là ai?")}</div>}
 if(session.gameType==="memory_owner"){if(effectiveRevealed)content=<Reveal big={secret?.memoryAuthorName||"Một người thân"} sub="đã lưu kỷ niệm này"/>;else content=mine.data?<Done ends={session.endsAtMs}/>:<div style={stack}>{session.memoryPreview.mediaUrl?<img src={session.memoryPreview.mediaUrl} style={memoryImg}/>:null}<div style={question}>{session.memoryPreview.caption}</div>{memberGuess("Ai đã lưu ký ức này?")}</div>}
 if(session.gameType==="truth_lie"){if(effectiveRevealed)content=<div style={stack}><b>Câu bịa của {session.subjectName}</b>{(subjectResponse?.textLines||[]).map((line,i)=><div style={{...question,...(secret?.lieIndex===i?lieBox:null)}} key={i}>{i+1}. {line}{secret?.lieIndex===i?<b> · CÂU BỊA ✨</b>:null}</div>)}</div>;else if(session.subjectUid===uid)content=mine.data?<Done ends={session.endsAtMs}/>:<div style={stack}><b>Viết 2 thật · 1 bịa</b>{truth.map((v,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><input className="bloom-field" value={v} onChange={e=>setTruth(a=>a.map((x,j)=>j===i?e.target.value:x))}/><button className="bloom-chip" data-active={lie===i} onClick={()=>setLie(i)}>Câu bịa</button></div>)}<button className="bloom-btn primary" disabled={busy||truth.some(x=>!x.trim())||lie==null} onClick={()=>void (async()=>{setBusy(true);try{await submitWebTruthStatements({familyId,session,uid,displayName:name,lines:truth,lieIndex:lie!})}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}})()}>Gửi 3 câu</button></div>;else content=!subjectResponse?<Waiting text={`${session.subjectName} đang nghĩ 3 câu…`}/>:mine.data?<Done ends={session.endsAtMs}/>:<div style={stack}>{subjectResponse.textLines.map((l,i)=><button key={i} style={{...statement,...(choice===i?statementActive:null)}} onClick={()=>setChoice(i)}>{i+1}. {l}</button>)}<button className="bloom-btn primary" disabled={choice==null||busy} onClick={()=>void submit({choiceIndex:choice})}>Chốt câu bịa</button></div>}
 if(session.gameType==="story_chain"){const publicRows=responses.items;const ordered=session.turnUids.map(id=>publicRows.find(r=>r.uid===id)).filter(Boolean) as HomeGameResponse[];const nextUid=session.turnUids.find(id=>!publicRows.some(r=>r.uid===id));content=<div style={stack}><div style={question}><b>Mở đầu</b><div>{session.prompts[0]?.prompt}</div></div>{ordered.map((r,i)=><div style={resultLine} key={r.uid}><strong>{i+1}. {r.displayName}</strong><span>{r.textLines[0]}</span></div>)}{!effectiveRevealed&&nextUid===uid&&!mine.data?<><textarea className="bloom-field" rows={3} value={story} onChange={e=>setStory(e.target.value)} placeholder="Nối tiếp câu chuyện…"/><button className="bloom-btn primary" disabled={!story.trim()||busy} onClick={()=>void submit({textLines:[story]})}>Gửi câu của tôi</button></>:!effectiveRevealed?<Waiting text={nextUid?`Đang tới lượt ${session.turnNames[session.turnUids.indexOf(nextUid)]}`:"Câu chuyện đã đủ lượt"}/>:null}</div>}
 if(session.gameType==="family_bingo"){content=<div style={stack}><div style={bingoGrid}>{session.bingoCellIds.map(id=>{const active=bingo.includes(id);return <button key={id} style={{...bingoCell,...(active?bingoActive:null)}} onClick={()=>{const next=active?bingo.filter(x=>x!==id):[...bingo,id];setBingo(next);void submit({selectedIds:next})}}>{getBingoCell(id)}{active?<b> ✓</b>:null}</button>})}</div><div style={small}>{bingo.length}/9 ô đã đánh dấu · tiến độ riêng của bạn</div></div>}
 return <div style={stack}><div style={metaLine}>{session.participantUids.length} người · {session.submittedUids.length} đã tham gia · {session.endsAtMs?`khép lại ${formatHomeGameDeadline(session.endsAtMs)}`:"đang chơi"}</div>{error?<InlineNotice tone="danger">{error}</InlineNotice>:null}{content}</div>;
}
function Done({ends}:{ends:number|null}){return <Waiting text={ends?`Bạn đã trả lời. Kết quả tự mở lúc ${formatHomeGameDeadline(ends)}.`:"Bạn đã trả lời."}/>};function Waiting({text}:{text:string}){return <div style={waitBox}>⌛ <span>{text}</span></div>};function Reveal({big,sub}:{big:string;sub:string}){return <div style={reveal}><div style={{fontSize:42}}>✨</div><h2 style={{margin:"4px 0"}}>{big}</h2><div style={small}>{sub}</div></div>};
function iconFor(t:HomeGameType){return t==="know_each_other"?"💗":t==="guess_person"?"🕵️":t==="memory_owner"?"🖼️":t==="truth_lie"?"✨":t==="story_chain"?"📖":"🌸"}
const gameTypeCard:React.CSSProperties={border:0,borderRadius:20,padding:14,display:"flex",alignItems:"center",gap:10,textAlign:"left",color:"#654d56",cursor:"pointer"};const gameIcon:React.CSSProperties={fontSize:28};const small:React.CSSProperties={fontSize:11,color:"#8f7880",lineHeight:1.45};const micro:React.CSSProperties={fontSize:9,fontWeight:850,color:"#b3687d",marginTop:4};const sessionRow:React.CSSProperties={border:"1px solid #f0dfe5",borderRadius:16,background:"#fff",padding:"11px 13px",display:"flex",alignItems:"center",gap:10,color:"#614b53",cursor:"pointer"};const stack:React.CSSProperties={display:"grid",gap:10};const metaLine:React.CSSProperties={fontSize:11,color:"#937b84",padding:"2px 0 6px"};const question:React.CSSProperties={padding:13,borderRadius:16,background:"#fff7f9",display:"grid",gap:7,fontSize:12,lineHeight:1.5};const category:React.CSSProperties={fontSize:9,fontWeight:900,color:"#ba657f",letterSpacing:".12em"};const optionGrid:React.CSSProperties={display:"flex",flexWrap:"wrap",gap:6};const resultLine:React.CSSProperties={display:"flex",justifyContent:"space-between",gap:12,padding:11,borderRadius:14,background:"#fff8fa",fontSize:12};const memoryImg:React.CSSProperties={width:"100%",maxHeight:280,objectFit:"cover",borderRadius:16};const lieBox:React.CSSProperties={background:"#fff0cc"};const statement:React.CSSProperties={border:"1px solid #efdce2",borderRadius:14,padding:12,background:"white",textAlign:"left",cursor:"pointer",color:"#664f58"};const statementActive:React.CSSProperties={background:"#fde5ed",borderColor:"#eaa8bd"};const waitBox:React.CSSProperties={padding:18,borderRadius:18,background:"#fff8fa",display:"flex",alignItems:"center",gap:10,color:"#826b73",fontSize:12};const reveal:React.CSSProperties={textAlign:"center",padding:20,borderRadius:20,background:"linear-gradient(145deg,#ffe8ef,#fff7ed)"};const bingoGrid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:6};const bingoCell:React.CSSProperties={minHeight:86,border:"1px solid #efdce2",borderRadius:14,padding:7,background:"#fff",fontSize:10,color:"#725c64",cursor:"pointer"};const bingoActive:React.CSSProperties={background:"#fde3eb",color:"#a34e68",fontWeight:800};
