import {
  Timestamp,arrayRemove,arrayUnion,collection,deleteDoc,doc,getDoc,getDocs,increment,limit,orderBy,query,runTransaction,serverTimestamp,setDoc,updateDoc,where,writeBatch,
} from "firebase/firestore";
import { webDb } from "../firebaseWeb";

const now=()=>new Date().toISOString();
const clean=(v:string,max=500)=>v.trim().replace(/\s+/g," ").slice(0,max);
const id=()=>crypto.randomUUID().replace(/-/g,"").slice(0,24);

export type WebMomentMedia={id:string;type:"image"|"video";secureUrl:string;publicId:string;thumbnailUrl?:string};
const mediaEnv={
 cloudName:process.env.EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME||"g7fnsxw5",
 imagePreset:process.env.EXPO_PUBLIC_CLOUDINARY_IMAGE_PRESET||"family_bloom_image",
 videoPreset:process.env.EXPO_PUBLIC_CLOUDINARY_VIDEO_PRESET||"family_bloom_video",
};

export type WebUploadMediaOptions={
 purpose?:"moment"|"avatar";
 entityType?:"moment"|"user";
 entityId?:string;
 familyIdForAsset?:string|null;
 folder?:string;
};

export async function uploadWebMedia(file:File,familyId:string,uid:string,onProgress?:(n:number)=>void,options:WebUploadMediaOptions={}):Promise<{media:WebMomentMedia;assetId:string}>{
 const isVideo=file.type.startsWith("video/");const preset=isVideo?mediaEnv.videoPreset:mediaEnv.imagePreset;
 if(!mediaEnv.cloudName||!preset)throw new Error("Thiếu cấu hình Cloudinary cho Web. Hãy đặt EXPO_PUBLIC_CLOUDINARY_CLOUD_NAME và upload preset trong .env.");
 const purpose=options.purpose||"moment";const entityType=options.entityType||"moment";const entityId=options.entityId||"web_pending";const familyIdForAsset=options.familyIdForAsset===undefined?familyId:options.familyIdForAsset;
 const folder=options.folder||`family-bloom/families/${familyId}/moments`;
 const assetId=`${uid}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;const assetRef=doc(webDb,`media_assets/${assetId}`);const createdAt=now();
 await setDoc(assetRef,{id:assetId,ownerUid:uid,familyId:familyIdForAsset,purpose,entityType,entityId,provider:"cloudinary",type:isVideo?"video":"image",secureUrl:null,publicId:null,thumbnailUrl:null,mimeType:file.type,fileName:file.name,status:"uploading",createdAt,updatedAt:createdAt});
 try{
  const form=new FormData();form.append("file",file);form.append("upload_preset",preset);form.append("folder",folder);
  const xhr=new XMLHttpRequest();const payload=await new Promise<any>((resolve,reject)=>{xhr.open("POST",`https://api.cloudinary.com/v1_1/${mediaEnv.cloudName}/${isVideo?"video":"image"}/upload`);xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress?.(Math.round(e.loaded/e.total*100))};xhr.onload=()=>xhr.status>=200&&xhr.status<300?resolve(JSON.parse(xhr.responseText)):reject(new Error(`Cloudinary HTTP ${xhr.status}`));xhr.onerror=()=>reject(new Error("Không tải được media lên Cloudinary."));xhr.send(form)});
  const secureUrl=String(payload.secure_url||"");const publicId=String(payload.public_id||"");if(!secureUrl||!publicId)throw new Error("Cloudinary không trả về media hợp lệ.");
  const thumbnailUrl=isVideo?secureUrl.replace(/\.[^/.]+$/,".jpg"):secureUrl;
  await updateDoc(assetRef,{secureUrl,publicId,thumbnailUrl,status:"uploaded",updatedAt:now()});
  return {assetId,media:{id:assetId,type:isVideo?"video":"image",secureUrl,publicId,thumbnailUrl}};
 }catch(e){await updateDoc(assetRef,{status:"failed",updatedAt:now()}).catch(()=>undefined);throw e}
}

export async function createMoment(input:{familyId:string;uid:string;name:string;avatarUrl?:string;caption:string;files:File[];personIds?:string[];notifyFamily?:boolean;onProgress?:(n:number)=>void}){
 const postRef=doc(collection(webDb,`families/${input.familyId}/moments`));const uploaded:{assetId:string;media:WebMomentMedia}[]=[];
 for(let i=0;i<input.files.length;i++){const one=await uploadWebMedia(input.files[i],input.familyId,input.uid,p=>input.onProgress?.(Math.round((i*100+p)/Math.max(1,input.files.length))));uploaded.push(one)}
 const t=now();const data={id:postRef.id,familyId:input.familyId,authorUid:input.uid,authorName:clean(input.name,80)||"Thành viên",...(input.avatarUrl?{authorAvatarUrl:input.avatarUrl}:{}),caption:input.caption.trim(),media:uploaded.map(x=>x.media),mediaAssetIds:uploaded.map(x=>x.assetId),personIds:Array.from(new Set(input.personIds||[])),timelineAudience:"family",notifyFamily:input.notifyFamily===true,visibility:"family",moderationStatus:"visible",moderatedByUid:null,moderatedAt:null,reactionCounts:{like:0,love:0,haha:0,wow:0,sad:0,celebrate:0},commentCount:0,createdAt:t,updatedAt:t};
 const batch=writeBatch(webDb);batch.set(postRef,data);uploaded.forEach(x=>batch.update(doc(webDb,`media_assets/${x.assetId}`),{entityId:postRef.id,status:"attached",updatedAt:t}));await batch.commit();return postRef.id;
}

export async function deleteOwnMoment(familyId:string,postId:string,uid:string){const ref=doc(webDb,`families/${familyId}/moments/${postId}`);const snap=await getDoc(ref);if(!snap.exists())return;if(snap.data().authorUid!==uid)throw new Error("Bạn chỉ có thể xóa Kỷ niệm do mình đăng.");await deleteDoc(ref)}
export async function setMomentReaction(familyId:string,postId:string,uid:string,reaction:"like"|"love"|"haha"|"wow"|"sad"|"celebrate"){
 const postRef=doc(webDb,`families/${familyId}/moments/${postId}`),reactRef=doc(webDb,`families/${familyId}/moments/${postId}/reactions/${uid}`);
 await runTransaction(webDb,async tx=>{const [p,r]=await Promise.all([tx.get(postRef),tx.get(reactRef)]);if(!p.exists())throw new Error("Kỷ niệm không còn tồn tại.");const raw=p.data();const counts={like:0,love:0,haha:0,wow:0,sad:0,celebrate:0,...(raw.reactionCounts||{})};const old=r.exists()?r.data().reaction:null;if(old===reaction){counts[reaction]=Math.max(0,(counts[reaction]||0)-1);tx.delete(reactRef)}else{if(old&&counts[old]!=null)counts[old]=Math.max(0,counts[old]-1);counts[reaction]=(counts[reaction]||0)+1;tx.set(reactRef,{uid,reaction,createdAt:r.exists()?r.data().createdAt:now(),updatedAt:now()})}tx.update(postRef,{reactionCounts:counts,updatedAt:now()})})
}
export async function addMomentComment(familyId:string,postId:string,uid:string,name:string,avatarUrl:string|undefined,text:string){const body=text.trim().slice(0,800);if(!body)return;const ref=doc(collection(webDb,`families/${familyId}/moments/${postId}/comments`));const postRef=doc(webDb,`families/${familyId}/moments/${postId}`);const t=now();await runTransaction(webDb,async tx=>{const p=await tx.get(postRef);if(!p.exists())throw new Error("Kỷ niệm không còn tồn tại.");tx.set(ref,{id:ref.id,postId,authorUid:uid,authorName:clean(name,80)||"Thành viên",...(avatarUrl?{authorAvatarUrl:avatarUrl}:{}),text:body,createdAt:t,updatedAt:t});tx.update(postRef,{commentCount:increment(1),updatedAt:t})})}
export async function listMomentComments(familyId:string,postId:string){const snap=await getDocs(query(collection(webDb,`families/${familyId}/moments/${postId}/comments`),orderBy("createdAt","asc"),limit(50)));return snap.docs.map(d=>({id:d.id,...d.data()} as any))}

export async function createEvent(input:{familyId:string;uid:string;title:string;dateISO:string;allDay:boolean;eventType:string;description?:string;location?:string;recurrence?:string;participantIds?:string[];personIds?:string[]}){const d=new Date(input.dateISO);if(Number.isNaN(d.getTime()))throw new Error("Ngày giờ không hợp lệ.");const ref=doc(collection(webDb,`families/${input.familyId}/events`));const t=now();const dateKey=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;await setDoc(ref,{id:ref.id,familyId:input.familyId,title:clean(input.title,160),dateISO:d.toISOString(),dateKey,year:d.getFullYear(),month:d.getMonth()+1,day:d.getDate(),allDay:input.allDay,eventType:input.eventType||"family",notificationLevel:"normal",participantsMode:(input.participantIds?.length?"selected":"all"),participantIds:input.participantIds||[],personIds:input.personIds||[],recurrence:input.recurrence||"none",description:clean(input.description||"",1200)||null,location:clean(input.location||"",240)||null,attachments:[],attachmentPublicIds:[],coverAttachmentId:null,createdByUid:input.uid,moderationStatus:"visible",moderatedByUid:null,moderatedAt:null,createdAt:t,updatedAt:t});return ref.id}
export async function updateEvent(familyId:string,eventId:string,patch:Record<string,unknown>){await updateDoc(doc(webDb,`families/${familyId}/events/${eventId}`),{...patch,updatedAt:now()})}
export async function deleteEvent(familyId:string,eventId:string){await deleteDoc(doc(webDb,`families/${familyId}/events/${eventId}`))}

export async function createPerson(input:{familyId:string;uid:string;displayName:string;gender:"male"|"female"|"other";nickname?:string;birthDate?:string;birthPlace?:string;lifeStatus?:"living"|"deceased"|"unknown";description?:string}){const ref=doc(collection(webDb,`families/${input.familyId}/persons`));const t=now();const birthYear=input.birthDate?Number(input.birthDate.slice(0,4)):null;await setDoc(ref,{id:ref.id,familyId:input.familyId,linkedUid:null,displayName:clean(input.displayName,120),gender:input.gender,nickname:clean(input.nickname||"",80)||null,birthDate:input.birthDate||null,birthYear:Number.isFinite(birthYear)?birthYear:null,birthPlace:clean(input.birthPlace||"",160)||null,deathDate:null,deathYear:null,lifeStatus:input.lifeStatus||"unknown",birthOrder:null,avatarUrl:null,description:clean(input.description||"",700)||null,createdByUid:input.uid,createdAt:t,updatedAt:t});return ref.id}
export async function updatePerson(familyId:string,personId:string,patch:Record<string,unknown>){await updateDoc(doc(webDb,`families/${familyId}/persons/${personId}`),{...patch,updatedAt:now()})}
export async function createRelationship(input:{familyId:string;uid:string;type:"parent_child"|"partner";personAId:string;personBId:string;subtype?:string;partnerStatus?:string}){if(input.personAId===input.personBId)throw new Error("Không thể tạo quan hệ với chính mình.");const [a,b]=input.type==="partner"?[input.personAId,input.personBId].sort():[input.personAId,input.personBId];const relId=input.type==="parent_child"?`pc_${a}_${b}`:`pt_${a}_${b}`;const ref=doc(webDb,`families/${input.familyId}/relationships/${relId}`);if((await getDoc(ref)).exists())throw new Error("Quan hệ này đã tồn tại.");const t=now();await setDoc(ref,{id:relId,familyId:input.familyId,type:input.type,personAId:a,personBId:b,subtype:input.type==="parent_child"?(input.subtype||"unknown"):null,partnerStatus:input.type==="partner"?(input.partnerStatus||"partner"):null,startDate:null,endDate:null,createdByUid:input.uid,createdAt:t,updatedAt:t});return relId}
export async function deleteRelationship(familyId:string,relationshipId:string){await deleteDoc(doc(webDb,`families/${familyId}/relationships/${relationshipId}`))}

export async function createWhisper(input:{familyId:string;uid:string;name:string;familyMemberUids:string[];audience:"family"|"direct";recipientUid?:string|null;recipientName?:string|null;message:string;emotion:string}){const message=input.message.trim();if(!message)throw new Error("Hãy viết lời thì thầm.");const ref=doc(collection(webDb,`families/${input.familyId}/homeWhispers`));const direct=input.audience==="direct";const recipientUid=direct?(input.recipientUid||null):null;const viewerUids=direct?Array.from(new Set([input.uid,recipientUid].filter(Boolean))):Array.from(new Set([...input.familyMemberUids,input.uid]));const t=now();const batch=writeBatch(webDb);batch.set(ref,{id:ref.id,familyId:input.familyId,authorUid:input.uid,authorName:clean(input.name,80)||"Người thân",audience:input.audience,recipientUid,recipientName:direct?(input.recipientName||null):null,viewerUids,message:message.slice(0,500),emotion:input.emotion||"heart",heartUids:[],createdAt:t,updatedAt:t,expireAt:Timestamp.fromDate(new Date(Date.now()+60*86400000))});if(direct&&recipientUid)batch.set(doc(webDb,`users/${recipientUid}/homeInbox/${ref.id}`),{id:ref.id,type:"home_whisper",familyId:input.familyId,sourceId:ref.id,senderUid:input.uid,senderName:clean(input.name,80)||"Người thân",recipientUid,title:"Bạn có một lời thì thầm 💌",body:`${clean(input.name,80)||"Một người thân"} vừa gửi một lời riêng cho bạn.`,createdAt:t,readAt:null});await batch.commit();return ref.id}
export async function toggleWhisperHeart(familyId:string,whisperId:string,uid:string,liked:boolean){await updateDoc(doc(webDb,`families/${familyId}/homeWhispers/${whisperId}`),{heartUids:liked?arrayUnion(uid):arrayRemove(uid),updatedAt:now()})}

export async function createPoll(input:{familyId:string;uid:string;name:string;question:string;description?:string;eligibleUids:string[];anonymous:boolean;expiresAt:Date}){const q=clean(input.question,220);if(!q)throw new Error("Hãy nhập nội dung cần cả nhà quyết định.");const eligible=Array.from(new Set([input.uid,...input.eligibleUids]));const expires=new Date(input.expiresAt);expires.setHours(23,59,59,999);const ref=doc(collection(webDb,`families/${input.familyId}/homePolls`));const t=now();await setDoc(ref,{id:ref.id,familyId:input.familyId,createdByUid:input.uid,createdByName:clean(input.name,80)||"Người thân",question:q,description:clean(input.description||"",1200),audience:"family",eligibleUids:eligible,eligibleCount:eligible.length,anonymous:input.anonymous,agreeCount:0,disagreeCount:0,votedCount:0,createdAt:t,updatedAt:t,expiresAt:Timestamp.fromDate(expires),deleteAt:Timestamp.fromDate(new Date(expires.getTime()+30*86400000))});return ref.id}
export async function votePoll(familyId:string,pollId:string,uid:string,name:string,choice:"agree"|"disagree") {const pRef=doc(webDb,`families/${familyId}/homePolls/${pollId}`),bRef=doc(webDb,`families/${familyId}/homePolls/${pollId}/ballots/${uid}`);await runTransaction(webDb,async tx=>{const [p,b]=await Promise.all([tx.get(pRef),tx.get(bRef)]);if(!p.exists())throw new Error("Cuộc bỏ phiếu không còn tồn tại.");const poll=p.data();if(!Array.isArray(poll.eligibleUids)||!poll.eligibleUids.includes(uid))throw new Error("Bạn không thuộc nhóm bỏ phiếu.");const old=b.exists()?b.data().choice:null;let agree=Number(poll.agreeCount||0),disagree=Number(poll.disagreeCount||0),voted=Number(poll.votedCount||0);if(!old){voted++;choice==="agree"?agree++:disagree++}else if(old!==choice){old==="agree"?agree--:disagree--;choice==="agree"?agree++:disagree++}const t=now();tx.set(bRef,{uid,displayName:poll.anonymous?"":clean(name,80),choice,createdAt:b.exists()?b.data().createdAt:t,updatedAt:t,deleteAt:poll.deleteAt});tx.update(pRef,{agreeCount:Math.max(0,agree),disagreeCount:Math.max(0,disagree),votedCount:Math.max(0,voted),updatedAt:t})})}

export async function createTimeCapsule(input:{familyId:string;uid:string;name:string;recipientUids:string[];previewMode:"hidden"|"locked";revealTheme:"warm"|"formal"|"festive";openAt:Date;title:string;message:string}){const recipients=Array.from(new Set(input.recipientUids.filter(x=>x&&x!==input.uid)));if(!recipients.length)throw new Error("Hãy chọn ít nhất một người nhận.");if(input.openAt.getTime()<=Date.now()+15000)throw new Error("Thời gian mở phải ở tương lai.");const ref=doc(collection(webDb,`families/${input.familyId}/homeTimeCapsules`));const t=now();const batch=writeBatch(webDb);batch.set(ref,{id:ref.id,familyId:input.familyId,createdByUid:input.uid,createdByName:clean(input.name,80)||"Người thân",audience:recipients.length>1?"selected":"selected",recipientUids:recipients,previewMode:input.previewMode,openAt:Timestamp.fromDate(input.openAt),revealTheme:input.revealTheme,createdAt:t,updatedAt:t});batch.set(doc(webDb,`families/${input.familyId}/homeTimeCapsules/${ref.id}/private/content`),{title:input.title.trim().slice(0,140),message:input.message.trim().slice(0,4000)});await batch.commit();return ref.id}
export async function openTimeCapsule(familyId:string,capsuleId:string,uid:string){const content=await getDoc(doc(webDb,`families/${familyId}/homeTimeCapsules/${capsuleId}/private/content`));if(!content.exists())throw new Error("Chưa thể mở nội dung Hộp thời gian.");const receipt=doc(webDb,`families/${familyId}/homeTimeCapsules/${capsuleId}/opens/${uid}`);if(!(await getDoc(receipt)).exists())await setDoc(receipt,{uid,openedAt:serverTimestamp()});await setDoc(doc(webDb,`families/${familyId}/homeTimeCapsules/${capsuleId}`),{openedByUids:arrayUnion(uid)},{merge:true});return content.data() as {title:string;message:string}}

export async function createFundTransaction(input:{familyId:string;uid:string;name:string;type:"income"|"expense";amountVnd:number;category:string;note:string;occurredOn:string}){const amount=Math.trunc(input.amountVnd);if(!Number.isFinite(amount)||amount<=0)throw new Error("Số tiền phải lớn hơn 0.");const txRef=doc(collection(webDb,`families/${input.familyId}/homeFundTransactions`));const summaryRef=doc(webDb,`families/${input.familyId}/homeFundMeta/summary`);const auditRef=doc(collection(webDb,`families/${input.familyId}/homeFundAudit`));const t=now(),monthKey=input.occurredOn.slice(0,7);await runTransaction(webDb,async tx=>{const s=await tx.get(summaryRef);const cur=s.exists()?s.data():{};const income=Number(cur.totalIncomeVnd||0),expense=Number(cur.totalExpenseVnd||0),balance=Number(cur.balanceVnd||0),count=Number(cur.transactionCount||0);const row={id:txRef.id,familyId:input.familyId,type:input.type,amountVnd:amount,category:input.category,note:clean(input.note,240),occurredOn:input.occurredOn,monthKey,createdByUid:input.uid,createdByName:clean(input.name,80)||"Người thân",createdAt:t,createdAtTs:serverTimestamp(),updatedAt:t,updatedByUid:input.uid,revision:1};tx.set(txRef,row);tx.set(auditRef,{id:auditRef.id,familyId:input.familyId,action:"create",transactionId:txRef.id,actorUid:input.uid,actorName:clean(input.name,80)||"Người thân",targetUid:null,detail:`${input.type==="income"?"Thu":"Chi"} ${amount.toLocaleString("vi-VN")}đ`,beforeLabel:null,afterLabel:clean(input.note,120)||null,createdAt:t});tx.set(summaryRef,{familyId:input.familyId,balanceVnd:balance+(input.type==="income"?amount:-amount),totalIncomeVnd:income+(input.type==="income"?amount:0),totalExpenseVnd:expense+(input.type==="expense"?amount:0),transactionCount:count+1,lastMutationId:txRef.id,lastMutationKind:"create",lastAuditId:auditRef.id,updatedByUid:input.uid,updatedAt:t},{merge:true})});return txRef.id}

export async function saveKitchenPreferences(familyId:string,uid:string,tags:string[]){await setDoc(doc(webDb,`families/${familyId}/homeKitchenPreferences/${uid}`),{familyId,uid,tags:Array.from(new Set(tags)),updatedAt:now()},{merge:true})}

export async function saveWebMemoryBook(input:{familyId:string;uid:string;id?:string;scope:"family"|"person";personId?:string|null;title:string;subtitle?:string;momentIds:string[]}){
 const ref=input.id?doc(webDb,`families/${input.familyId}/memoryBooks/${input.id}`):doc(collection(webDb,`families/${input.familyId}/memoryBooks`));
 const existing=input.id?await getDoc(ref):null;const t=now();
 const payload={id:ref.id,familyId:input.familyId,scope:input.scope,personId:input.scope==="person"?(input.personId||null):null,title:clean(input.title,180)||"Kỷ yếu Bloom",subtitle:clean(input.subtitle||"",400),coverMomentId:input.momentIds[0]||null,momentIds:Array.from(new Set(input.momentIds)).slice(0,120),createdByUid:existing?.exists()?String(existing.data().createdByUid||input.uid):input.uid,createdAt:existing?.exists()?String(existing.data().createdAt||t):t,updatedAt:t};
 await setDoc(ref,payload);return payload;
}
