import {
  collection, doc, getDoc, getDocs, limit, orderBy, query, runTransaction, where,
} from "firebase/firestore";
import { webDb } from "../firebaseWeb";
import { GAME_COPY, GUESS_PERSON_CLUES, KNOW_EACH_OTHER_QUESTIONS, BINGO_CELLS, STORY_STARTERS } from "../../data/games/homeGameQuestionBank";
import { getHomeGamePlayWindow, HOME_GAME_MAX_ACTIVE_PER_TYPE } from "../../services/home/homeGamePolicy";
import type { HomeGamePrompt, HomeGameResponse, HomeGameSecret, HomeGameSession, HomeGameStatus, HomeGameType } from "../../types/homeLiving";

const nowIso=()=>new Date().toISOString();
const hash=(input:string)=>{let v=2166136261;for(let i=0;i<input.length;i++){v^=input.charCodeAt(i);v=Math.imul(v,16777619)}return v>>>0};
const seededPick=<T,>(items:T[],count:number,seed:string)=>{const pool=[...items];let state=hash(seed)||1;const next=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/0x100000000};for(let i=pool.length-1;i>0;i--){const j=Math.floor(next()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]]}return pool.slice(0,Math.min(count,pool.length))};
const isSubject=(t:HomeGameType)=>["know_each_other","guess_person","truth_lie"].includes(t);
const slotPath=(familyId:string,t:HomeGameType,id:number)=>`families/${familyId}/homeGameActiveSlots/${t}_${id}`;
const sessionPath=(familyId:string,id:string)=>`families/${familyId}/homeGameSessions/${id}`;
const responsePath=(familyId:string,id:string,uid:string)=>`${sessionPath(familyId,id)}/responses/${uid}`;
const secretPath=(familyId:string,id:string)=>`${sessionPath(familyId,id)}/secrets/main`;
const rotationPath=(familyId:string,t:HomeGameType)=>`families/${familyId}/homeGameRotations/${t}`;

export async function createWebHomeGame(input:{familyId:string;creatorUid:string;creatorName:string;gameType:HomeGameType;members:Array<{uid:string;displayName?:string;shortName?:string}>}){
 const window=getHomeGamePlayWindow();if(!window.canCreate)throw new Error(window.message||"Trò chơi mới chưa mở.");
 const participants=input.members.filter(m=>!!m.uid);if(!participants.some(m=>m.uid===input.creatorUid))participants.unshift({uid:input.creatorUid,displayName:input.creatorName});if(participants.length<2&&input.gameType!=="family_bingo")throw new Error("Nhà Mình cần ít nhất 2 thành viên để bắt đầu trò này.");
 const ref=doc(collection(webDb,`families/${input.familyId}/homeGameSessions`));const createdAt=nowIso();const seed=`${input.familyId}:${ref.id}:${createdAt}`;let memoryPreview={caption:"",mediaUrl:"",mediaType:"none" as const};let memorySecret:any=null;
 if(input.gameType==="memory_owner"){
   const snap=await getDocs(query(collection(webDb,`families/${input.familyId}/moments`),orderBy("createdAt","desc"),limit(60)));const moments=snap.docs.map(d=>({id:d.id,...d.data()} as any)).filter(m=>(String(m.caption||"").trim()||m.media?.length)&&participants.some(p=>p.uid===m.authorUid));if(!moments.length)throw new Error("Nhà Mình chưa có Moment phù hợp để chơi.");const chosen=seededPick(moments,1,seed)[0];const media=chosen.media?.[0];memoryPreview={caption:String(chosen.caption||"Một khoảnh khắc của Nhà Mình").slice(0,700),mediaUrl:String(media?.thumbnailUrl||media?.secureUrl||""),mediaType:media?.type==="video"?"video":media?.type==="image"?"image":"none"};memorySecret={memoryAuthorUid:chosen.authorUid,memoryAuthorName:chosen.authorName,memoryMomentId:chosen.id};
 }
 const slots=Array.from({length:HOME_GAME_MAX_ACTIVE_PER_TYPE},(_,i)=>doc(webDb,slotPath(input.familyId,input.gameType,i)));const rotation=doc(webDb,rotationPath(input.familyId,input.gameType));
 await runTransaction(webDb,async tx=>{const slotSnaps=[];for(const r of slots)slotSnaps.push(await tx.get(r));const rotationSnap=isSubject(input.gameType)?await tx.get(rotation):null;const slotId=slotSnaps.findIndex(s=>!s.exists()||Number(s.data()?.endsAtMs||0)<=Date.now());if(slotId<0)throw new Error("Trò này đang có 4 lượt hoạt động. Chờ một lượt khép lại nhé.");
   let prompts:HomeGamePrompt[]=[];let subjectUid:string|null=null;let subjectName:string|null=null;let turnUids:string[]=[];let turnNames:string[]=[];let bingoCellIds:string[]=[];let secret:HomeGameSecret|null=null;
   if(isSubject(input.gameType)){const raw=rotationSnap?.exists()?rotationSnap.data():null;let used:string[]=raw?.playDateKey===window.playDateKey&&Array.isArray(raw?.usedUids)?raw.usedUids.filter((u:any)=>participants.some(p=>p.uid===u)):[];let candidates=participants.filter(p=>!used.includes(p.uid));if(!candidates.length){used=[];candidates=[...participants]}if(!used.length&&candidates.length>1){const non=candidates.filter(p=>p.uid!==input.creatorUid);if(non.length)candidates=non}const subject=seededPick(candidates,1,`${seed}:subject`)[0]||participants[0];subjectUid=subject?.uid||null;subjectName=subject?.displayName||subject?.shortName||"Người thân";tx.set(rotation,{familyId:input.familyId,gameType:input.gameType,playDateKey:window.playDateKey,usedUids:Array.from(new Set([...used,subjectUid].filter(Boolean))),updatedAt:createdAt});}
   if(input.gameType==="know_each_other")prompts=seededPick(KNOW_EACH_OTHER_QUESTIONS,5,seed);else if(input.gameType==="guess_person"){prompts=seededPick(GUESS_PERSON_CLUES,3,seed);secret={sessionId:ref.id,familyId:input.familyId,allowedUids:Array.from(new Set([input.creatorUid,subjectUid].filter((x):x is string=>!!x))),subjectUid,subjectName,memoryAuthorUid:null,memoryAuthorName:null,memoryMomentId:null,lieIndex:null,createdAt,updatedAt:createdAt}}else if(input.gameType==="memory_owner"){secret={sessionId:ref.id,familyId:input.familyId,allowedUids:[input.creatorUid],subjectUid:null,subjectName:null,memoryAuthorUid:memorySecret?.memoryAuthorUid||null,memoryAuthorName:memorySecret?.memoryAuthorName||null,memoryMomentId:memorySecret?.memoryMomentId||null,lieIndex:null,createdAt,updatedAt:createdAt}}else if(input.gameType==="truth_lie"){secret={sessionId:ref.id,familyId:input.familyId,allowedUids:Array.from(new Set([input.creatorUid,subjectUid].filter((x):x is string=>!!x))),subjectUid,subjectName,memoryAuthorUid:null,memoryAuthorName:null,memoryMomentId:null,lieIndex:null,createdAt,updatedAt:createdAt}}else if(input.gameType==="story_chain"){const index=hash(seed)%STORY_STARTERS.length;prompts=[{id:`story_${index}`,category:"Mở đầu",prompt:STORY_STARTERS[index],options:[]}];const order=seededPick(participants,participants.length,seed);turnUids=order.map(x=>x.uid);turnNames=order.map(x=>x.displayName||x.shortName||"Thành viên")}else if(input.gameType==="family_bingo"){bingoCellIds=seededPick(BINGO_CELLS.map((_,i)=>i),9,seed).map(i=>`bingo_${i}`)}
   const session:HomeGameSession={id:ref.id,familyId:input.familyId,gameType:input.gameType,title:GAME_COPY[input.gameType].title,createdByUid:input.creatorUid,createdByName:input.creatorName.slice(0,80)||"Người thân",participantUids:participants.map(x=>x.uid),participantNames:participants.map(x=>x.displayName||x.shortName||"Thành viên"),status:"playing",prompts,subjectUid,subjectName,turnUids,turnNames,bingoCellIds,memoryPreview,submittedUids:[],endsAtMs:window.endsAtMs,playDateKey:window.playDateKey,slotId,createdAt,updatedAt:createdAt};
   tx.set(slots[slotId],{familyId:input.familyId,gameType:input.gameType,slotId,sessionId:ref.id,subjectUid,playDateKey:window.playDateKey,endsAtMs:window.endsAtMs,updatedAt:createdAt});tx.set(ref,session as any);if(secret)tx.set(doc(webDb,secretPath(input.familyId,ref.id)),secret as any);
 });return ref.id;
}

export async function getWebHomeGameSecret(familyId:string,sessionId:string){try{const s=await getDoc(doc(webDb,secretPath(familyId,sessionId)));return s.exists()?({...(s.data() as any)} as HomeGameSecret):null}catch{return null}}
export async function submitWebHomeGameResponse(input:{familyId:string;session:HomeGameSession;uid:string;displayName:string;answers?:string[];textLines?:string[];selectedIds?:string[];guessUid?:string|null;guessName?:string|null;choiceIndex?:number|null;public?:boolean}){const sRef=doc(webDb,sessionPath(input.familyId,input.session.id));const rRef=doc(webDb,responsePath(input.familyId,input.session.id,input.uid));const updatedAt=nowIso();await runTransaction(webDb,async tx=>{const sSnap=await tx.get(sRef);if(!sSnap.exists())throw new Error("Ván chơi không còn tồn tại.");const raw=sSnap.data() as HomeGameSession;if(raw.endsAtMs&&Date.now()>=raw.endsAtMs)throw new Error("Lượt chơi đã khép lại.");const existing=await tx.get(rRef);const expectedPublic=input.session.gameType==="story_chain"||input.session.gameType==="family_bingo"||((input.session.gameType==="guess_person"||input.session.gameType==="truth_lie")&&input.session.subjectUid===input.uid);const response:HomeGameResponse={uid:input.uid,displayName:input.displayName.slice(0,80)||"Thành viên",answers:(input.answers||[]).slice(0,10).map(x=>x.slice(0,220)),textLines:(input.textLines||[]).slice(0,3).map(x=>x.trim().slice(0,400)),selectedIds:Array.from(new Set((input.selectedIds||[]).slice(0,9))),guessUid:input.guessUid||null,guessName:input.guessName?.slice(0,80)||null,choiceIndex:Number.isInteger(input.choiceIndex)?input.choiceIndex!:null,public:expectedPublic,submittedAt:existing.exists()?String(existing.data()?.submittedAt||updatedAt):updatedAt,updatedAt};tx.set(rRef,response as any);const submitted=Array.isArray(raw.submittedUids)?raw.submittedUids:[];tx.update(sRef,{submittedUids:Array.from(new Set([...submitted,input.uid])),updatedAt});});}
export async function submitWebTruthStatements(input:{familyId:string;session:HomeGameSession;uid:string;displayName:string;lines:string[];lieIndex:number}){if(input.lines.filter(Boolean).length!==3)throw new Error("Hãy viết đủ 3 câu.");const secretRef=doc(webDb,secretPath(input.familyId,input.session.id));await submitWebHomeGameResponse({familyId:input.familyId,session:input.session,uid:input.uid,displayName:input.displayName,textLines:input.lines,public:true});await runTransaction(webDb,async tx=>{const sec=await tx.get(secretRef);if(!sec.exists()||sec.data()?.subjectUid!==input.uid)throw new Error("Chỉ người ra câu mới được đánh dấu câu bịa.");tx.update(secretRef,{lieIndex:input.lieIndex,updatedAt:nowIso()});});}
export async function revealWebHomeGame(familyId:string,session:HomeGameSession,uid:string,status:HomeGameStatus="revealed"){if(session.createdByUid!==uid)throw new Error("Chỉ người tạo ván mới được mở kết quả.");if(session.endsAtMs&&Date.now()<session.endsAtMs)throw new Error("Ván sẽ tự mở khi hết thời gian.");await runTransaction(webDb,async tx=>{const ref=doc(webDb,sessionPath(familyId,session.id));const snap=await tx.get(ref);if(!snap.exists())return;tx.update(ref,{status,updatedAt:nowIso()});});}
