import { useMemo, useRef, useState } from "react";
import { useWebAuth } from "../context/WebAuthContext";
import { useWebFamily } from "../context/WebFamilyContext";
import { useWebCollection } from "../hooks/useWebCollection";
import { DataError, EmptyState, Skeleton, WebCard, WebPage } from "../components/WebPrimitives";
import { FormRow, InlineNotice, WebModal } from "../components/WebOverlay";
import { createPerson, createRelationship, deleteRelationship, updatePerson } from "../services/webFeatureService";
type Person={id:string;displayName?:string;nickname?:string;gender?:"male"|"female"|"other";birthDate?:string|null;birthYear?:number|null;birthPlace?:string|null;lifeStatus?:string;avatarUrl?:string|null;linkedUid?:string|null;description?:string|null};
type Rel={id:string;type?:"parent_child"|"partner";personAId?:string;personBId?:string;partnerStatus?:string|null;subtype?:string|null};
type Point={x:number;y:number};
export default function GraphWebPage(){const auth=useWebAuth();const f=useWebFamily();const people=useWebCollection<Person>(f.activeFamilyId?`families/${f.activeFamilyId}/persons`:null);const rels=useWebCollection<Rel>(f.activeFamilyId?`families/${f.activeFamilyId}/relationships`:null);const layout=useMemo(()=>makeLayout(people.items,rels.items),[people.items,rels.items]);const [focus,setFocus]=useState<string|null>(null);const [zoom,setZoom]=useState(1);const [pan,setPan]=useState({x:30,y:30});const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);const pointers=useRef(new Map<number,{x:number;y:number}>());const pinch=useRef<{distance:number;zoom:number}|null>(null);const selected=people.items.find(p=>p.id===(focus||people.items.find(x=>x.linkedUid===auth.user?.uid)?.id||people.items[0]?.id))||null;const [personOpen,setPersonOpen]=useState(false);const [relationOpen,setRelationOpen]=useState(false);const [editOpen,setEditOpen]=useState(false);const [error,setError]=useState<string|null>(null);
 const reset=()=>{setZoom(1);setPan({x:30,y:30})};
 return <WebPage eyebrow="PHẢ HỆ" title="Cây Nhà Mình" subtitle="Cùng persons/relationships với Android. Web hỗ trợ pan, zoom, focus, thêm/sửa người và tạo quan hệ." action={<div style={{display:"flex",gap:7}}><button className="bloom-btn secondary" onClick={reset}>Về giữa</button><button className="bloom-btn" onClick={()=>setPersonOpen(true)}>＋ Thêm người</button></div>}>
  <DataError message={people.error||rels.error}/>
  {people.loading||rels.loading?<Skeleton height={520}/>:people.items.length?<div className="bloom-two-pane">
   <WebCard style={{padding:10,overflow:"hidden"}}><div style={toolbar}><button className="bloom-btn ghost" style={round} onClick={()=>setZoom(z=>Math.max(.45,z-.15))}>−</button><span style={zoomText}>{Math.round(zoom*100)}%</span><button className="bloom-btn ghost" style={round} onClick={()=>setZoom(z=>Math.min(1.8,z+.15))}>＋</button><span style={{fontSize:11,color:"#9a8089",marginLeft:"auto"}}>Kéo nền · chụm 2 ngón để zoom · chạm người để focus</span></div><div style={viewport} onDoubleClick={reset} onWheel={e=>{e.preventDefault();setZoom(z=>Math.max(.45,Math.min(1.8,z+(e.deltaY<0?.08:-.08))))}} onPointerDown={e=>{const target=e.target as HTMLElement;if(target.closest?.("[data-graph-node='true']"))return;e.currentTarget.setPointerCapture?.(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===1){drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};pinch.current=null}else if(pointers.current.size===2){const pts=[...pointers.current.values()];pinch.current={distance:Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y),zoom};drag.current=null}}} onPointerMove={e=>{if(!pointers.current.has(e.pointerId))return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size>=2&&pinch.current){const pts=[...pointers.current.values()].slice(0,2);const distance=Math.max(1,Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y));setZoom(Math.max(.45,Math.min(1.8,pinch.current.zoom*(distance/pinch.current.distance))));return}if(drag.current)setPan({x:drag.current.px+e.clientX-drag.current.x,y:drag.current.py+e.clientY-drag.current.y})}} onPointerUp={e=>{pointers.current.delete(e.pointerId);if(pointers.current.size===0){drag.current=null;pinch.current=null}else if(pointers.current.size===1){const pt=[...pointers.current.values()][0];drag.current={x:pt.x,y:pt.y,px:pan.x,py:pan.y};pinch.current=null}}} onPointerCancel={e=>{pointers.current.delete(e.pointerId);if(!pointers.current.size){drag.current=null;pinch.current=null}}}>
    <svg width="100%" height="560" viewBox={`0 0 ${Math.max(900,layout.width)} ${Math.max(620,layout.height)}`} style={{display:"block",touchAction:"none"}}><g transform={`translate(${pan.x} ${pan.y}) scale(${zoom})`}>
     {rels.items.map(r=>{const a=layout.points.get(r.personAId||""),b=layout.points.get(r.personBId||"");if(!a||!b)return null;const partner=r.type==="partner";const x1=a.x+90,y1=a.y+46,x2=b.x+90,y2=b.y+46;return <path key={r.id} d={partner?`M ${x1} ${y1} L ${x2} ${y2}`:`M ${x1} ${y1+42} C ${x1} ${y1+95}, ${x2} ${y2-60}, ${x2} ${y2-12}`} fill="none" stroke={partner?"#df8ca5":"#d5b6c0"} strokeWidth={partner?3:2} strokeDasharray={partner?"0":"5 4"}/>})}
     {people.items.map(p=>{const pt=layout.points.get(p.id)!;const active=selected?.id===p.id;return <g key={p.id} data-graph-node="true" transform={`translate(${pt.x} ${pt.y})`} onClick={e=>{e.stopPropagation();setFocus(p.id)}} style={{cursor:"pointer"}}><rect width="180" height="92" rx="22" fill={active?"#fde5ed":"#fff"} stroke={active?"#df7899":"#ead5dc"} strokeWidth={active?3:1.5}/><circle cx="34" cy="34" r="21" fill={p.gender==="male"?"#e5efff":p.gender==="female"?"#ffe7ef":"#efe9f7"}/>{p.avatarUrl?<image href={p.avatarUrl} x="13" y="13" width="42" height="42" clipPath="inset(0 round 50%)"/>:<text x="34" y="41" textAnchor="middle" fontSize="18" fill="#84636e">{p.gender==="male"?"♂":p.gender==="female"?"♀":"•"}</text>}<text x="64" y="31" fontSize="14" fontWeight="800" fill="#4d3840">{clip(p.displayName||"Người thân",16)}</text><text x="64" y="50" fontSize="10" fill="#967c85">{p.nickname?`“${clip(p.nickname,16)}”`:p.birthYear?`Sinh ${p.birthYear}`:"Chưa rõ năm sinh"}</text><text x="18" y="77" fontSize="9" fill="#b06b81">{p.linkedUid===auth.user?.uid?"BẠN":p.lifeStatus==="deceased"?"TƯỞNG NHỚ":"THÀNH VIÊN"}</text></g>})}
    </g></svg>
   </div></WebCard>
   <div>{selected?<WebCard style={{position:"sticky",top:96}}><div style={inspectorTop}>{selected.avatarUrl?<img src={selected.avatarUrl} style={bigAvatar}/>:<div style={{...bigAvatar,display:"grid",placeItems:"center",background:"#fde8ef",fontSize:28}}>{selected.gender==="male"?"♂":selected.gender==="female"?"♀":"•"}</div>}<div><div style={{fontSize:10,fontWeight:900,color:"#c06a84",letterSpacing:".12em"}}>HỒ SƠ</div><h2 style={{margin:"3px 0 2px",fontSize:23}}>{selected.displayName}</h2><div style={muted}>{selected.nickname||selected.birthPlace||"Người thân trong Nhà Mình"}</div></div></div><div style={detailGrid}><Detail label="Năm sinh" value={selected.birthYear?String(selected.birthYear):"Chưa rõ"}/><Detail label="Trạng thái" value={selected.lifeStatus==="deceased"?"Đã mất":selected.lifeStatus==="living"?"Đang sống":"Chưa rõ"}/></div>{selected.description?<p style={desc}>{selected.description}</p>:null}<div style={actions}><button className="bloom-btn secondary" onClick={()=>setEditOpen(true)}>Sửa hồ sơ</button><button className="bloom-btn" onClick={()=>setRelationOpen(true)}>＋ Quan hệ</button></div><div style={{marginTop:16}}><b style={{fontSize:12}}>Quan hệ trực tiếp</b>{rels.items.filter(r=>r.personAId===selected.id||r.personBId===selected.id).map(r=><div key={r.id} style={relRow}><span>{r.type==="partner"?"♡":"↕"} {nameOf(people.items,r.personAId===selected.id?r.personBId:r.personAId)}</span><button className="bloom-btn danger" style={{padding:"5px 8px"}} onClick={()=>f.activeFamilyId&&confirm("Xóa quan hệ này?")&&void deleteRelationship(f.activeFamilyId,r.id)}>×</button></div>)}</div></WebCard>:null}</div>
  </div>:<EmptyState icon="🌳" title="Chưa có dữ liệu phả hệ" copy="Thêm người đầu tiên ngay trên web."/>}
  {error?<InlineNotice tone="danger">{error}</InlineNotice>:null}
  <PersonModal open={personOpen} onClose={()=>setPersonOpen(false)} onSave={async data=>{if(!f.activeFamilyId||!auth.user)return;try{const personId=await createPerson({familyId:f.activeFamilyId,uid:auth.user.uid,...data});setFocus(personId);setPersonOpen(false)}catch(e){setError(e instanceof Error?e.message:String(e))}}}/>
  {selected?<PersonModal open={editOpen} onClose={()=>setEditOpen(false)} initial={selected} onSave={async data=>{if(!f.activeFamilyId)return;await updatePerson(f.activeFamilyId,selected.id,{...data,birthYear:data.birthDate?Number(data.birthDate.slice(0,4)):null});setEditOpen(false)}}/>:null}
  {selected?<RelationModal open={relationOpen} onClose={()=>setRelationOpen(false)} selected={selected} people={people.items} onSave={async data=>{if(!f.activeFamilyId||!auth.user)return;try{await createRelationship({familyId:f.activeFamilyId,uid:auth.user.uid,...data});setRelationOpen(false)}catch(e){setError(e instanceof Error?e.message:String(e))}}}/>:null}
 </WebPage>}
function PersonModal({open,onClose,onSave,initial}:{open:boolean;onClose():void;onSave(data:any):Promise<void>;initial?:Person}){const [name,setName]=useState(initial?.displayName||"");const [gender,setGender]=useState(initial?.gender||"other");const [nickname,setNickname]=useState(initial?.nickname||"");const [birthDate,setBirthDate]=useState(initial?.birthDate||"");const [birthPlace,setBirthPlace]=useState(initial?.birthPlace||"");const [lifeStatus,setLifeStatus]=useState(initial?.lifeStatus||"unknown");const [description,setDescription]=useState(initial?.description||"");return <WebModal open={open} onClose={onClose} title={initial?"Sửa hồ sơ":"Thêm người vào Phả hệ"} sheet><FormRow label="Tên"><input className="bloom-field" value={name} onChange={e=>setName(e.target.value)}/></FormRow><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><FormRow label="Giới tính"><select className="bloom-field" value={gender} onChange={e=>setGender(e.target.value as any)}><option value="male">Nam</option><option value="female">Nữ</option><option value="other">Khác</option></select></FormRow><FormRow label="Ngày sinh"><input className="bloom-field" type="date" value={birthDate||""} onChange={e=>setBirthDate(e.target.value)}/></FormRow></div><FormRow label="Tên gọi thân mật"><input className="bloom-field" value={nickname||""} onChange={e=>setNickname(e.target.value)}/></FormRow><FormRow label="Nơi sinh"><input className="bloom-field" value={birthPlace||""} onChange={e=>setBirthPlace(e.target.value)}/></FormRow><FormRow label="Trạng thái"><select className="bloom-field" value={lifeStatus} onChange={e=>setLifeStatus(e.target.value)}><option value="unknown">Chưa rõ</option><option value="living">Đang sống</option><option value="deceased">Đã mất</option></select></FormRow><FormRow label="Ghi chú"><textarea className="bloom-field bloom-textarea" value={description||""} onChange={e=>setDescription(e.target.value)}/></FormRow><div style={actions}><button className="bloom-btn secondary" onClick={onClose}>Hủy</button><button className="bloom-btn" disabled={!name.trim()} onClick={()=>void onSave({displayName:name,gender,nickname:nickname||null,birthDate:birthDate||null,birthPlace:birthPlace||null,lifeStatus,description:description||null})}>Lưu</button></div></WebModal>}
function RelationModal({open,onClose,onSave,selected,people}:{open:boolean;onClose():void;onSave(data:any):Promise<void>;selected:Person;people:Person[]}){const [type,setType]=useState<"parent_child"|"partner">("parent_child");const [other,setOther]=useState("");const [direction,setDirection]=useState<"parent"|"child">("parent");return <WebModal open={open} onClose={onClose} title="Thêm quan hệ" sheet><FormRow label="Loại quan hệ"><select className="bloom-field" value={type} onChange={e=>setType(e.target.value as any)}><option value="parent_child">Cha/mẹ – con</option><option value="partner">Vợ/chồng/đối tác</option></select></FormRow>{type==="parent_child"?<FormRow label={`Vai trò của ${selected.displayName}`}><select className="bloom-field" value={direction} onChange={e=>setDirection(e.target.value as any)}><option value="parent">Là cha/mẹ</option><option value="child">Là con</option></select></FormRow>:null}<FormRow label="Người còn lại"><select className="bloom-field" value={other} onChange={e=>setOther(e.target.value)}><option value="">Chọn người</option>{people.filter(p=>p.id!==selected.id).map(p=><option value={p.id} key={p.id}>{p.displayName}</option>)}</select></FormRow><div style={actions}><button className="bloom-btn secondary" onClick={onClose}>Hủy</button><button className="bloom-btn" disabled={!other} onClick={()=>void onSave(type==="partner"?{type,personAId:selected.id,personBId:other,partnerStatus:"partner"}:{type,personAId:direction==="parent"?selected.id:other,personBId:direction==="parent"?other:selected.id,subtype:"unknown"})}>Tạo quan hệ</button></div></WebModal>}
function Detail({label,value}:{label:string;value:string}){return <div style={{background:"#fff5f7",borderRadius:14,padding:10}}><div style={{fontSize:9,color:"#b06b81",fontWeight:900,letterSpacing:".1em"}}>{label.toUpperCase()}</div><b style={{fontSize:12}}>{value}</b></div>};function nameOf(ps:Person[],id?:string){return ps.find(x=>x.id===id)?.displayName||"Người thân"}function clip(x:string,n:number){return x.length>n?x.slice(0,n-1)+"…":x}
function makeLayout(ps:Person[],rs:Rel[]){const parents=rs.filter(r=>r.type==="parent_child"&&r.personAId&&r.personBId);const depth=new Map<string,number>(),vis=new Set<string>();const calc=(pid:string):number=>{if(depth.has(pid))return depth.get(pid)!;if(vis.has(pid))return 0;vis.add(pid);const pp=parents.filter(r=>r.personBId===pid).map(r=>r.personAId!);const d=pp.length?Math.max(...pp.map(x=>calc(x)+1)):0;vis.delete(pid);depth.set(pid,d);return d};ps.forEach(p=>calc(p.id));const rows=new Map<number,Person[]>();ps.forEach(p=>{const d=depth.get(p.id)||0;rows.set(d,[...(rows.get(d)||[]),p])});const points=new Map<string,Point>();let maxW=0;[...rows.entries()].sort((a,b)=>a[0]-b[0]).forEach(([d,row])=>{row.sort((a,b)=>(a.birthYear||9999)-(b.birthYear||9999));row.forEach((p,i)=>points.set(p.id,{x:i*220,y:d*160}));maxW=Math.max(maxW,row.length*220)});return {points,width:maxW+220,height:(Math.max(0,...depth.values())+1)*160+180}}
const toolbar:React.CSSProperties={display:"flex",alignItems:"center",gap:6,padding:"2px 2px 10px"};const round:React.CSSProperties={width:36,height:36,padding:0};const zoomText:React.CSSProperties={width:48,textAlign:"center",fontSize:11,fontWeight:850,color:"#8b7079"};const viewport:React.CSSProperties={height:"clamp(480px,64dvh,680px)",overflow:"hidden",touchAction:"none",borderRadius:20,background:"radial-gradient(circle at 50% 35%,#fff 0,#fffaf8 70%)",border:"1px solid #f1dfe5",cursor:"grab"};const inspectorTop:React.CSSProperties={display:"flex",gap:12,alignItems:"center"};const bigAvatar:React.CSSProperties={width:68,height:68,borderRadius:23,objectFit:"cover"};const muted:React.CSSProperties={fontSize:11,color:"#957c85"};const detailGrid:React.CSSProperties={display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:16};const desc:React.CSSProperties={fontSize:12,lineHeight:1.6,color:"#6e5861",whiteSpace:"pre-wrap"};const actions:React.CSSProperties={display:"flex",gap:8,justifyContent:"flex-end",marginTop:16};const relRow:React.CSSProperties={display:"flex",alignItems:"center",justifyContent:"space-between",gap:8,padding:"9px 0",fontSize:12,borderBottom:"1px solid #f4e5e9"};
