import { limit, orderBy } from "firebase/firestore";
import { useMemo, useState } from "react";
import { useWebAuth } from "../context/WebAuthContext";
import { useWebFamily } from "../context/WebFamilyContext";
import { useWebCollection } from "../hooks/useWebCollection";
import { DataError, EmptyState, Skeleton, WebCard, WebPage } from "../components/WebPrimitives";
import { FormRow, InlineNotice, WebModal } from "../components/WebOverlay";
import { createEvent, deleteEvent, updateEvent } from "../services/webFeatureService";
type Event={id:string;title?:string;dateISO?:string;eventType?:string;description?:string;location?:string;recurrence?:string;createdByUid?:string;participantsMode?:"all"|"selected";participantIds?:string[]};
const TYPES=["family","birthday","anniversary","gathering","wedding","travel","memorial","other"];
export default function PlannerWebPage(){const auth=useWebAuth();const f=useWebFamily();const c=useMemo(()=>[orderBy("dateISO","asc"),limit(120)],[]);const q=useWebCollection<Event>(f.activeFamilyId?`families/${f.activeFamilyId}/events`:null,c);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Event|null>(null);const [title,setTitle]=useState("");const [date,setDate]=useState("");const [type,setType]=useState("family");const [location,setLocation]=useState("");const [desc,setDesc]=useState("");const [recurrence,setRecurrence]=useState("none");const [participantsMode,setParticipantsMode]=useState<"all"|"selected">("all");const [participantIds,setParticipantIds]=useState<string[]>([]);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
 const show=(e?:Event)=>{setEditing(e||null);setTitle(e?.title||"");setDate(e?.dateISO?toLocalInput(e.dateISO):toLocalInput(new Date(Date.now()+3600000).toISOString()));setType(e?.eventType||"family");setLocation(e?.location||"");setDesc(e?.description||"");setRecurrence(e?.recurrence||"none");setParticipantsMode(e?.participantsMode||"all");setParticipantIds(e?.participantIds||[]);setError(null);setOpen(true)};
 const save=async()=>{if(!f.activeFamilyId||!auth.user||busy)return;setBusy(true);setError(null);try{const iso=new Date(date).toISOString();if(editing){const d=new Date(iso);await updateEvent(f.activeFamilyId,editing.id,{title:title.trim(),dateISO:iso,dateKey:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,year:d.getFullYear(),month:d.getMonth()+1,day:d.getDate(),eventType:type,location:location.trim()||null,description:desc.trim()||null,recurrence,participantsMode,participantIds:participantsMode==="selected"?participantIds:[]})}else await createEvent({familyId:f.activeFamilyId,uid:auth.user.uid,title,dateISO:iso,allDay:false,eventType:type,description:desc,location,recurrence,participantIds:participantsMode==="selected"?participantIds:[]});setOpen(false)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <WebPage eyebrow="LỊCH NHÀ MÌNH" title="Mọi dịp quan trọng, ở cùng một nơi" subtitle="Tạo, chỉnh sửa và theo dõi sự kiện cùng Firestore với Android." action={<button className="bloom-btn" onClick={()=>show()}>＋ Thêm sự kiện</button>}>
  <DataError message={q.error}/>
  {q.loading?<Skeleton height={220}/>:q.items.length?<div style={list}>{q.items.map(e=><WebCard key={e.id}><div style={row}><div style={dateBox}><b>{day(e.dateISO)}</b><span>{month(e.dateISO)}</span></div><div style={{minWidth:0}}><div style={tag}>{label(e.eventType)}</div><h3 style={titleStyle}>{e.title||"Sự kiện Nhà Mình"}</h3><div style={muted}>{time(e.dateISO)}{e.location?` · ${e.location}`:""}{e.recurrence&&e.recurrence!=="none"?` · ${e.recurrence}`:""}</div>{e.description?<p style={descStyle}>{e.description}</p>:null}<div style={{display:"flex",gap:6,marginTop:10}}><button className="bloom-btn ghost" onClick={()=>show(e)}>Sửa</button><button className="bloom-btn danger" onClick={()=>{if(f.activeFamilyId&&confirm("Xóa sự kiện này?"))void deleteEvent(f.activeFamilyId,e.id)}}>Xóa</button></div></div></div></WebCard>)}</div>:<EmptyState icon="🗓️" title="Lịch đang trống" copy="Thêm sự kiện đầu tiên ngay trên web."/>}
  <WebModal open={open} onClose={()=>!busy&&setOpen(false)} title={editing?"Sửa sự kiện":"Thêm sự kiện"} sheet>
   <FormRow label="Tên sự kiện"><input className="bloom-field" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ví dụ: Sinh nhật mẹ"/></FormRow>
   <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><FormRow label="Ngày & giờ"><input className="bloom-field" type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></FormRow><FormRow label="Loại"><select className="bloom-field" value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></FormRow></div>
   <FormRow label="Địa điểm"><input className="bloom-field" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Ở đâu?"/></FormRow>
   <FormRow label="Người tham gia"><div style={{display:"flex",gap:8,marginBottom:8}}><button type="button" className="bloom-chip" data-active={participantsMode==="all"} onClick={()=>{setParticipantsMode("all");setParticipantIds([])}}>Cả nhà</button><button type="button" className="bloom-chip" data-active={participantsMode==="selected"} onClick={()=>setParticipantsMode("selected")}>Chọn người</button></div>{participantsMode==="selected"?<div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{f.members.map(m=>{const active=participantIds.includes(m.uid);return <button type="button" className="bloom-chip" data-active={active} key={m.uid} onClick={()=>setParticipantIds(active?participantIds.filter(x=>x!==m.uid):[...participantIds,m.uid])}>{m.displayName||m.shortName||"Thành viên"}</button>})}</div>:null}</FormRow>
   <FormRow label="Lặp lại"><select className="bloom-field" value={recurrence} onChange={e=>setRecurrence(e.target.value)}><option value="none">Không lặp</option><option value="daily">Hàng ngày</option><option value="weekly">Hàng tuần</option><option value="monthly">Hàng tháng</option><option value="yearly">Hàng năm</option></select></FormRow><FormRow label="Ghi chú"><textarea className="bloom-field bloom-textarea" value={desc} onChange={e=>setDesc(e.target.value)}/></FormRow>
   {error?<InlineNotice tone="danger">{error}</InlineNotice>:null}<div style={actions}><button className="bloom-btn secondary" onClick={()=>setOpen(false)}>Hủy</button><button className="bloom-btn" disabled={busy||!title.trim()||!date} onClick={()=>void save()}>{busy?"Đang lưu…":"Lưu"}</button></div>
  </WebModal>
 </WebPage>}
const toLocalInput=(iso:string)=>{const d=new Date(iso);const z=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`};const d=(v?:string)=>v?new Date(v):null;const day=(v?:string)=>String(d(v)?.getDate()||"—").padStart(2,"0");const month=(v?:string)=>d(v)?.toLocaleDateString("vi-VN",{month:"short"})||"";const time=(v?:string)=>d(v)?.toLocaleString("vi-VN",{dateStyle:"full",timeStyle:"short"})||"";const label=(x?:string)=>({birthday:"SINH NHẬT",memorial:"TƯỞNG NIỆM",anniversary:"KỶ NIỆM",gathering:"SUM HỌP",wedding:"HỶ SỰ",travel:"CHUYẾN ĐI",family:"GIA ĐÌNH",other:"KHÁC"} as Record<string,string>)[x||""]||"NHÀ MÌNH";const list:React.CSSProperties={display:"flex",flexDirection:"column",gap:12};const row:React.CSSProperties={display:"grid",gridTemplateColumns:"64px 1fr",gap:15};const dateBox:React.CSSProperties={height:64,borderRadius:18,background:"#fde8ef",color:"#b45f79",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"};const tag:React.CSSProperties={fontSize:9,fontWeight:900,letterSpacing:".12em",color:"#c16884"};const titleStyle:React.CSSProperties={margin:"3px 0 5px",fontSize:18};const muted:React.CSSProperties={fontSize:12,color:"#927a83"};const descStyle:React.CSSProperties={fontSize:13,lineHeight:1.5,color:"#6c575f",margin:"10px 0 0"};const actions:React.CSSProperties={display:"flex",justifyContent:"flex-end",gap:8,marginTop:16};
