export type FamilyGraphPrototypeGender = "male" | "female" | "unknown";
export type FamilyGraphPrototypeLifeStatus = "living" | "deceased" | "unknown";
export type FamilyGraphPrototypeRelationKind =
  | "bac"
  | "co"
  | "chu"
  | "di"
  | "sibling"
  | "grandchild";

export type FamilyGraphPrototypePerson = {
  id: string;
  displayName: string;
  shortName: string;
  gender: FamilyGraphPrototypeGender;
  birthYear?: number;
  birthDate?: string;
  deathYear?: number;
  deathDate?: string;
  generation: number;
  linkedAccount: boolean;
  linkedUid?: string;
  avatarUrl?: string;
  lifeStatus: FamilyGraphPrototypeLifeStatus;
  birthPlace?: string;
  description?: string;
  roleLabel?: string;
  relationBadge?: {
    kind: FamilyGraphPrototypeRelationKind;
    label: string;
  };
  relationSummary: string[];
  timeline: Array<{ year: string; title: string; description: string }>;
  albumLabels: string[];
  x: number;
  y: number;
};

export type FamilyGraphPrototypeConnection = {
  id: string;
  fromId: string;
  toId: string;
  type: "parent_child" | "partner";
};

export const FAMILY_GRAPH_CANVAS = {
  // Refine v5: giữ mật độ gần mockup đã duyệt nhưng mở rộng ngang vừa đủ
  // để có cô/bác/chú/dì và các nhánh không có con cháu.
  width: 1020,
  // Phase 6.4 visual-compat uses a 216px generation pitch: roomier than 6.3,
  // but still compact enough to preserve the soft family-tree composition.
  height: 1120,
  nodeWidth: 128,
  nodeHeight: 124,
};

export const FAMILY_GRAPH_PROTOTYPE_PEOPLE: FamilyGraphPrototypePerson[] = [
  {
    id: "binh",
    displayName: "Nguyễn Văn Bình",
    shortName: "Ông Bình",
    gender: "male",
    birthYear: 1910,
    deathYear: 1985,
    generation: 1,
    linkedAccount: false,
    lifeStatus: "deceased",
    birthPlace: "Nam Định",
    description: "Ông nội của Nam, người được con cháu nhắc lại qua nhiều câu chuyện gia đình.",
    roleLabel: "Ông nội",
    relationSummary: ["Vợ/Chồng: Trần Thị Hoa", "Con: Nguyễn Văn Đức, Nguyễn Văn Hùng, Nguyễn Thị Hạnh, Nguyễn Văn Phúc"],
    timeline: [
      { year: "1910", title: "Chào đời", description: "Sinh tại Nam Định." },
      { year: "1936", title: "Lập gia đình", description: "Kết duyên cùng bà Trần Thị Hoa." },
      { year: "1985", title: "Qua đời", description: "Gia đình lưu giữ nhiều câu chuyện về ông." },
    ],
    albumLabels: ["Ảnh gia đình", "Kỷ niệm xưa"],
    x: 250,
    y: 18,
  },
  {
    id: "hoa",
    displayName: "Trần Thị Hoa",
    shortName: "Bà Hoa",
    gender: "female",
    birthYear: 1915,
    deathYear: 1990,
    generation: 1,
    linkedAccount: false,
    lifeStatus: "deceased",
    birthPlace: "Nam Định",
    description: "Bà nội của Nam, người giữ nếp nhà và những câu chuyện truyền lại cho con cháu.",
    roleLabel: "Bà nội",
    relationSummary: ["Vợ/Chồng: Nguyễn Văn Bình", "Con: Nguyễn Văn Đức, Nguyễn Văn Hùng, Nguyễn Thị Hạnh, Nguyễn Văn Phúc"],
    timeline: [
      { year: "1915", title: "Chào đời", description: "Sinh tại Nam Định." },
      { year: "1936", title: "Lập gia đình", description: "Kết duyên cùng ông Nguyễn Văn Bình." },
      { year: "1990", title: "Qua đời", description: "Con cháu tiếp tục lưu giữ ký ức về bà." },
    ],
    albumLabels: ["Chân dung", "Ảnh gia đình"],
    x: 390,
    y: 18,
  },
  {
    id: "khang",
    displayName: "Lê Văn Khang",
    shortName: "Ông Khang",
    gender: "male",
    birthYear: 1913,
    deathYear: 1988,
    generation: 1,
    linkedAccount: false,
    lifeStatus: "deceased",
    birthPlace: "Hà Nam",
    description: "Ông ngoại của Nam trong nhánh ngoại của mock graph.",
    roleLabel: "Ông ngoại",
    relationSummary: ["Vợ/Chồng: Phạm Thị Diệp", "Con: Lê Thị Mai, Lê Thị Thủy"],
    timeline: [{ year: "1913", title: "Chào đời", description: "Sinh tại Hà Nam." }],
    albumLabels: ["Ảnh xưa"],
    x: 650,
    y: 18,
  },
  {
    id: "diep",
    displayName: "Phạm Thị Diệp",
    shortName: "Bà Diệp",
    gender: "female",
    birthYear: 1918,
    deathYear: 1996,
    generation: 1,
    linkedAccount: false,
    lifeStatus: "deceased",
    birthPlace: "Hà Nam",
    description: "Bà ngoại của Nam trong nhánh ngoại của mock graph.",
    roleLabel: "Bà ngoại",
    relationSummary: ["Vợ/Chồng: Lê Văn Khang", "Con: Lê Thị Mai, Lê Thị Thủy"],
    timeline: [{ year: "1918", title: "Chào đời", description: "Sinh tại Hà Nam." }],
    albumLabels: ["Ảnh xưa"],
    x: 790,
    y: 18,
  },
  {
    id: "bac-duc",
    displayName: "Nguyễn Văn Đức",
    shortName: "Bác Đức",
    gender: "male",
    birthYear: 1937,
    generation: 2,
    linkedAccount: false,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Anh trai của ông Hùng; nhánh mẫu không có con cháu để kiểm tra nhánh kết thúc.",
    roleLabel: "Bác",
    relationBadge: { kind: "bac", label: "Bác" },
    relationSummary: ["Cha: Nguyễn Văn Bình", "Mẹ: Trần Thị Hoa", "Em: Nguyễn Văn Hùng"],
    timeline: [{ year: "1937", title: "Chào đời", description: "Sinh tại Hà Nội." }],
    albumLabels: ["Ảnh gia đình"],
    x: 40,
    y: 164,
  },
  {
    id: "co-hanh",
    displayName: "Nguyễn Thị Hạnh",
    shortName: "Cô Hạnh",
    gender: "female",
    birthYear: 1944,
    generation: 2,
    linkedAccount: false,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Em gái của ông Hùng; một nhánh collateral không có hậu duệ trong mock data.",
    roleLabel: "Cô",
    relationBadge: { kind: "co", label: "Cô" },
    relationSummary: ["Cha: Nguyễn Văn Bình", "Mẹ: Trần Thị Hoa", "Anh: Nguyễn Văn Hùng"],
    timeline: [{ year: "1944", title: "Chào đời", description: "Sinh tại Hà Nội." }],
    albumLabels: ["Ảnh gia đình"],
    x: 180,
    y: 164,
  },
  {
    id: "hung",
    displayName: "Nguyễn Văn Hùng",
    shortName: "Ông Hùng",
    gender: "male",
    birthYear: 1940,
    deathYear: 2005,
    generation: 2,
    linkedAccount: false,
    lifeStatus: "deceased",
    birthPlace: "Hà Nội",
    description: "Cha của Nam, một người điềm đạm và luôn đặt gia đình lên trước.",
    roleLabel: "Cha",
    relationSummary: ["Cha: Nguyễn Văn Bình", "Mẹ: Trần Thị Hoa", "Vợ/Chồng: Lê Thị Mai", "Con: Nguyễn Văn Nam"],
    timeline: [
      { year: "1940", title: "Chào đời", description: "Sinh tại Hà Nội." },
      { year: "1965", title: "Lập gia đình", description: "Kết duyên cùng bà Lê Thị Mai." },
      { year: "2005", title: "Qua đời", description: "Được con cháu nhớ đến qua những câu chuyện gia đình." },
    ],
    albumLabels: ["Gia đình", "Tuổi trẻ"],
    x: 320,
    y: 164,
  },
  {
    id: "mai",
    displayName: "Lê Thị Mai",
    shortName: "Bà Mai",
    gender: "female",
    birthYear: 1942,
    generation: 2,
    linkedAccount: true,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Mẹ của Nam, người luôn gắn kết các thành viên trong gia đình.",
    roleLabel: "Mẹ",
    relationSummary: ["Cha: Lê Văn Khang", "Mẹ: Phạm Thị Diệp", "Vợ/Chồng: Nguyễn Văn Hùng", "Con: Nguyễn Văn Nam"],
    timeline: [
      { year: "1942", title: "Chào đời", description: "Sinh tại Hà Nội." },
      { year: "1965", title: "Lập gia đình", description: "Kết duyên cùng ông Nguyễn Văn Hùng." },
      { year: "2026", title: "Hiện tại", description: "Vẫn thường xuyên gặp gỡ con cháu." },
    ],
    albumLabels: ["Con cháu", "Ngày sum họp", "Ảnh xưa"],
    x: 470,
    y: 164,
  },
  {
    id: "chu-phuc",
    displayName: "Nguyễn Văn Phúc",
    shortName: "Chú Phúc",
    gender: "male",
    birthYear: 1948,
    generation: 2,
    linkedAccount: false,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Em trai của ông Hùng; nhánh mẫu kết thúc tại đây, không có con cháu.",
    roleLabel: "Chú",
    relationBadge: { kind: "chu", label: "Chú" },
    relationSummary: ["Cha: Nguyễn Văn Bình", "Mẹ: Trần Thị Hoa", "Anh: Nguyễn Văn Hùng"],
    timeline: [{ year: "1948", title: "Chào đời", description: "Sinh tại Hà Nội." }],
    albumLabels: ["Ảnh gia đình"],
    x: 620,
    y: 164,
  },
  {
    id: "di-thuy",
    displayName: "Lê Thị Thủy",
    shortName: "Dì Thủy",
    gender: "female",
    birthYear: 1946,
    generation: 2,
    linkedAccount: false,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Em gái của bà Mai; nhánh mẫu không có hậu duệ để test nhánh trống.",
    roleLabel: "Dì",
    relationBadge: { kind: "di", label: "Dì" },
    relationSummary: ["Cha: Lê Văn Khang", "Mẹ: Phạm Thị Diệp", "Chị: Lê Thị Mai"],
    timeline: [{ year: "1946", title: "Chào đời", description: "Sinh tại Hà Nội." }],
    albumLabels: ["Ảnh gia đình"],
    x: 820,
    y: 164,
  },
  {
    id: "nam",
    displayName: "Nguyễn Văn Nam",
    shortName: "Anh Nam",
    gender: "male",
    birthYear: 1968,
    generation: 3,
    linkedAccount: true,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Một người cha tận tâm, luôn yêu thương và chăm lo cho gia đình.",
    roleLabel: "Focus mặc định",
    relationSummary: [
      "Cha: Nguyễn Văn Hùng",
      "Mẹ: Lê Thị Mai",
      "Vợ/Chồng: Phạm Thị Lan",
      "Bác: Nguyễn Văn Đức",
      "Cô: Nguyễn Thị Hạnh",
      "Chú: Nguyễn Văn Phúc",
      "Dì: Lê Thị Thủy",
      "Con: Nguyễn Minh, Nguyễn Thị Hà, Nguyễn Hoàng, Nguyễn Thị Thu",
    ],
    timeline: [
      { year: "1968", title: "Chào đời", description: "Sinh tại Hà Nội." },
      { year: "1989", title: "Lập gia đình", description: "Kết duyên cùng Phạm Thị Lan." },
      { year: "2026", title: "Hiện tại", description: "Là focus person mặc định của prototype." },
    ],
    albumLabels: ["Gia đình nhỏ", "Du lịch", "Ngày lễ", "Kỷ niệm"],
    x: 360,
    y: 310,
  },
  {
    id: "lan",
    displayName: "Phạm Thị Lan",
    shortName: "Chị Lan",
    gender: "female",
    birthYear: 1970,
    generation: 3,
    linkedAccount: true,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Luôn quan tâm đến mọi người và là người ghi lại nhiều khoảnh khắc gia đình.",
    roleLabel: "Vợ",
    relationSummary: ["Vợ/Chồng: Nguyễn Văn Nam", "Con: Nguyễn Minh, Nguyễn Thị Hà, Nguyễn Hoàng, Nguyễn Thị Thu"],
    timeline: [
      { year: "1970", title: "Chào đời", description: "Sinh tại Hà Nội." },
      { year: "1989", title: "Lập gia đình", description: "Kết duyên cùng Nguyễn Văn Nam." },
      { year: "2026", title: "Hiện tại", description: "Thường xuyên cập nhật album gia đình." },
    ],
    albumLabels: ["Gia đình", "Bếp nhà", "Chuyến đi"],
    x: 500,
    y: 310,
  },
  {
    id: "minh",
    displayName: "Nguyễn Minh",
    shortName: "Minh",
    gender: "male",
    birthYear: 1990,
    generation: 4,
    linkedAccount: true,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Anh cả trong thế hệ con của Nam và Lan.",
    roleLabel: "Con",
    relationBadge: { kind: "sibling", label: "Anh em" },
    relationSummary: ["Cha: Nguyễn Văn Nam", "Mẹ: Phạm Thị Lan", "Anh/chị/em: Hà, Hoàng, Thu", "Con: Nguyễn Gia Bảo"],
    timeline: [
      { year: "1990", title: "Chào đời", description: "Sinh tại Hà Nội." },
      { year: "2018", title: "Đón thành viên mới", description: "Gia Bảo chào đời." },
    ],
    albumLabels: ["Gia Bảo", "Gia đình nhỏ"],
    x: 120,
    y: 466,
  },
  {
    id: "ha",
    displayName: "Nguyễn Thị Hà",
    shortName: "Hà",
    gender: "female",
    birthYear: 1992,
    generation: 4,
    linkedAccount: true,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Người thích lưu lại những dịp cả nhà quây quần bên nhau.",
    roleLabel: "Con",
    relationBadge: { kind: "sibling", label: "Anh em" },
    relationSummary: ["Cha: Nguyễn Văn Nam", "Mẹ: Phạm Thị Lan", "Anh/chị/em: Minh, Hoàng, Thu", "Con: Nguyễn Khánh An"],
    timeline: [
      { year: "1992", title: "Chào đời", description: "Sinh tại Hà Nội." },
      { year: "2020", title: "Đón thành viên mới", description: "Khánh An chào đời." },
    ],
    albumLabels: ["Khánh An", "Ngày sum họp"],
    x: 310,
    y: 466,
  },
  {
    id: "hoang",
    displayName: "Nguyễn Hoàng",
    shortName: "Hoàng",
    gender: "male",
    birthYear: 1995,
    generation: 4,
    linkedAccount: false,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Person mẫu chưa liên kết với tài khoản Family Bloom.",
    roleLabel: "Con",
    relationBadge: { kind: "sibling", label: "Anh em" },
    relationSummary: ["Cha: Nguyễn Văn Nam", "Mẹ: Phạm Thị Lan", "Anh/chị/em: Minh, Hà, Thu", "Con: Nguyễn Gia Huy"],
    timeline: [
      { year: "1995", title: "Chào đời", description: "Sinh tại Hà Nội." },
      { year: "2022", title: "Đón thành viên mới", description: "Gia Huy chào đời." },
    ],
    albumLabels: ["Gia Huy"],
    x: 500,
    y: 466,
  },
  {
    id: "thu",
    displayName: "Nguyễn Thị Thu",
    shortName: "Thu",
    gender: "female",
    birthYear: 1998,
    generation: 4,
    linkedAccount: true,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Em út trong thế hệ con; nhánh này chưa có con cháu.",
    roleLabel: "Con",
    relationBadge: { kind: "sibling", label: "Anh em" },
    relationSummary: ["Cha: Nguyễn Văn Nam", "Mẹ: Phạm Thị Lan", "Anh/chị/em: Minh, Hà, Hoàng"],
    timeline: [
      { year: "1998", title: "Chào đời", description: "Sinh tại Hà Nội." },
      { year: "2026", title: "Hiện tại", description: "Đang liên kết với một tài khoản Family Bloom." },
    ],
    albumLabels: ["Bạn bè", "Gia đình"],
    x: 690,
    y: 466,
  },
  {
    id: "gia-bao",
    displayName: "Nguyễn Gia Bảo",
    shortName: "Gia Bảo",
    gender: "male",
    birthYear: 2018,
    generation: 5,
    linkedAccount: false,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Thế hệ cháu trong prototype Family Graph.",
    roleLabel: "Cháu",
    relationBadge: { kind: "grandchild", label: "Cháu" },
    relationSummary: ["Cha: Nguyễn Minh", "Ông: Nguyễn Văn Nam", "Bà: Phạm Thị Lan"],
    timeline: [{ year: "2018", title: "Chào đời", description: "Một thành viên của thế hệ thứ năm." }],
    albumLabels: ["Tuổi thơ"],
    x: 120,
    y: 650,
  },
  {
    id: "khanh-an",
    displayName: "Nguyễn Khánh An",
    shortName: "Khánh An",
    gender: "female",
    birthYear: 2020,
    generation: 5,
    linkedAccount: false,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Thế hệ cháu trong prototype Family Graph.",
    roleLabel: "Cháu",
    relationBadge: { kind: "grandchild", label: "Cháu" },
    relationSummary: ["Mẹ: Nguyễn Thị Hà", "Ông: Nguyễn Văn Nam", "Bà: Phạm Thị Lan"],
    timeline: [{ year: "2020", title: "Chào đời", description: "Một thành viên của thế hệ thứ năm." }],
    albumLabels: ["Tuổi thơ"],
    x: 310,
    y: 650,
  },
  {
    id: "gia-huy",
    displayName: "Nguyễn Gia Huy",
    shortName: "Gia Huy",
    gender: "male",
    birthYear: 2022,
    generation: 5,
    linkedAccount: false,
    lifeStatus: "living",
    birthPlace: "Hà Nội",
    description: "Thế hệ cháu trong prototype Family Graph.",
    roleLabel: "Cháu",
    relationBadge: { kind: "grandchild", label: "Cháu" },
    relationSummary: ["Cha: Nguyễn Hoàng", "Ông: Nguyễn Văn Nam", "Bà: Phạm Thị Lan"],
    timeline: [{ year: "2022", title: "Chào đời", description: "Một thành viên của thế hệ thứ năm." }],
    albumLabels: ["Tuổi thơ"],
    x: 500,
    y: 650,
  },
];

export const FAMILY_GRAPH_PROTOTYPE_CONNECTIONS: FamilyGraphPrototypeConnection[] = [
  { id: "partner-binh-hoa", fromId: "binh", toId: "hoa", type: "partner" },
  { id: "parent-binh-bac", fromId: "binh", toId: "bac-duc", type: "parent_child" },
  { id: "parent-hoa-bac", fromId: "hoa", toId: "bac-duc", type: "parent_child" },
  { id: "parent-binh-co", fromId: "binh", toId: "co-hanh", type: "parent_child" },
  { id: "parent-hoa-co", fromId: "hoa", toId: "co-hanh", type: "parent_child" },
  { id: "parent-binh-hung", fromId: "binh", toId: "hung", type: "parent_child" },
  { id: "parent-hoa-hung", fromId: "hoa", toId: "hung", type: "parent_child" },
  { id: "parent-binh-chu", fromId: "binh", toId: "chu-phuc", type: "parent_child" },
  { id: "parent-hoa-chu", fromId: "hoa", toId: "chu-phuc", type: "parent_child" },

  { id: "partner-khang-diep", fromId: "khang", toId: "diep", type: "partner" },
  { id: "parent-khang-mai", fromId: "khang", toId: "mai", type: "parent_child" },
  { id: "parent-diep-mai", fromId: "diep", toId: "mai", type: "parent_child" },
  { id: "parent-khang-di", fromId: "khang", toId: "di-thuy", type: "parent_child" },
  { id: "parent-diep-di", fromId: "diep", toId: "di-thuy", type: "parent_child" },

  { id: "partner-hung-mai", fromId: "hung", toId: "mai", type: "partner" },
  { id: "parent-hung-nam", fromId: "hung", toId: "nam", type: "parent_child" },
  { id: "parent-mai-nam", fromId: "mai", toId: "nam", type: "parent_child" },

  { id: "partner-nam-lan", fromId: "nam", toId: "lan", type: "partner" },
  { id: "parent-nam-minh", fromId: "nam", toId: "minh", type: "parent_child" },
  { id: "parent-lan-minh", fromId: "lan", toId: "minh", type: "parent_child" },
  { id: "parent-nam-ha", fromId: "nam", toId: "ha", type: "parent_child" },
  { id: "parent-lan-ha", fromId: "lan", toId: "ha", type: "parent_child" },
  { id: "parent-nam-hoang", fromId: "nam", toId: "hoang", type: "parent_child" },
  { id: "parent-lan-hoang", fromId: "lan", toId: "hoang", type: "parent_child" },
  { id: "parent-nam-thu", fromId: "nam", toId: "thu", type: "parent_child" },
  { id: "parent-lan-thu", fromId: "lan", toId: "thu", type: "parent_child" },

  { id: "parent-minh-bao", fromId: "minh", toId: "gia-bao", type: "parent_child" },
  { id: "parent-ha-an", fromId: "ha", toId: "khanh-an", type: "parent_child" },
  { id: "parent-hoang-huy", fromId: "hoang", toId: "gia-huy", type: "parent_child" },
];

export const FAMILY_GRAPH_DEFAULT_FOCUS_ID = "nam";
